### PR TITLE
[WIP] Moving MSMQ into its own project

### PR DESCRIPTION
**Pull request by johnsimons**
Time has come to move MSMQ into its own package.

## Main Reasons
1. By keeping MSMQ in the core, core is being shaped after it, which is not a good thing and makes us constantly think about other transports as an after thought;
2. Other transports are now more popular, so no need to have a default anymore;
3. Unless you have been hibernating for the last year, .NET Core is coming and with it lots of intereting challenges, one of them is to prepare our framework to support it.
As part of this preparation we need to remove System.Messaging from the core as a dependency as Messaging is not supported in either NET Core,Version=v5.0, .NET Core (Cross-platform),Version=v5.0 and ASP.NET 5,Version=v1.0.

This issue is part of https://github.com/Particular/PlatformDevelopment/issues/300
## Still left to do
- [ ] Create a transport agnostic impl of `TransportDefinition` for testing purposes, I actually think we need multiple of these to test all the scenarios;
- [ ] Deal with obsoletes;
- [ ] Document `TransportDefinition` usage;

### CODE REVIEW

**Comment by Scooletz** [comment]
Is it project for now, and later on a separate solution?

**Comment by johnsimons** [comment]
@Scooletz that would be the ultimate goal.
Wondering if @andreasohlund file transport is ready for prime time ?

**Comment by johnsimons** [comment]
I wonder how hard is to create a mock transport that tests all possible scenario permutations from a core perspective, @Particular/nservicebus thoughts ?

**Comment by andreasohlund** [comment]
I had all the acceptance tests green so I'd propose we rebase the filebased transport branch and see how far away we are?

**Comment by johnsimons** [comment]
@andreasohlund not sure the filebased transport supports all permutations we want to test against ?

From the top of my head I would say we want:
- test with DTC;
- test with some kind of native transactions;
- test without transactions;
- test as a broker with native pub/sub;
- test as a broker, no pub/sub


pretty sure I have missed a few other scenarios, @yvesgoeleven what else ?

**Comment by yvesgoeleven** [comment]
@johnsimons native deferal & TTBR come to mind

**Comment by colin-higgins** [comment]
Can we start by pulling MSMQ out into a nuget package and referencing that nuget package in the tests project?

**Comment by johnsimons** [comment]
@colin-higgins that is what I have done so far, but is just a temporary workaround for now

**Comment by andreasohlund** [comment]
>test with DTC;

Not possible

>test with some kind of native transactions;

Dev transport has "native transactions"

>test without transactions;

possible

> test as a broker with native pub/sub;

Not currently but I had plans to support native pub sub (to get config free routing for both events and commands for developers)

>test as a broker, no pub/sub

Not sure what this means?

**Comment by danielmarbach** [comment]
I could provide the DTC impl if required

**Comment by johnsimons** [comment]
> I could provide the DTC impl if required

@danielmarbach sure, u talking about extending the file based transport or just writing a mock one ?

**Comment by johnsimons** [comment]
IMO, I would go with specialised mock transports to test all the permutations that the core supports and test the file based transport on its own

**Comment by johnsimons** [comment]
@Particular/nservicebus what are people reactions of making this PR part of the v6 release ?
I have updated the description with reasons for this change, but the reason I see this as v6 is because of our yearly release schedule that if we are not to break MSMQ free from the core now, we wait a year for it and that may be too late because .NET Core is coming earlier then that I believe.

**Comment by andreasohlund** [comment]
The development transport is now rebased and passes all tests (except msmq specific ones) https://github.com/Particular/NServiceBus/pull/2950

**Comment by danielmarbach** [comment]
Still needs a rebase

**Comment by timbussmann** [comment]
Which epic/story does this belong to?

**Comment by andreasohlund** [comment]
@timbussmann https://github.com/Particular/PlatformDevelopment/issues/300 (description updated)

**Pull request closed without merging**
