### PR TITLE
[WIP] Fix RetryPolicy called multiple times

### PR DESCRIPTION
**Pull request by boblangley**
Pull request for #3443

- Failing acceptance test has been added. 
    - Backported overload to EndpointConfigurationBuilder to facilitate writing the acceptance test.
- Updated Fody to fix compile issues in VS2015

The actual behavior change has not yet been implemented pending discussion in #3443

### CODE REVIEW

**Comment by boblangley** [comment]
@Particular/nservicebus-maintainers /  @indualagarsamy . I implemented the header-based solution, please review.

**Comment by danielmarbach** [comment]
@boblangley PR should not go directly against the master branch. Normally what we do is create a hotfix-x.y.z branch and the do the commit on this branch. You can also PR against that hotfix branch. We can have a chat when you are online. 

That being said there is a discussion restarted if we should really backport this. I made this PR [WIP] so that nobody merges it

**Comment by ramonsmits** [comment]
@boblangley @danielmarbach This is linked to milestone 5.2.15 but I assume it should not be part of it?

**Comment by boblangley** [comment]
@ramonsmits Correct the issue was moved to the backlog. I unlinked the issue but not this pull request. I have removed the milestone.

**Pull request closed without merging**
