### PR TITLE
obsolete TransportConfig.MaximumConcurrencyLevel setting

### PR DESCRIPTION
**Pull request by timbussmann**
Removes the `TransportConfig.MaximumConcurrencyLevel` setting and enforces the code first API.

see #3311 

docs PR: https://github.com/Particular/docs.particular.net/pull/1136

### CODE REVIEW

**Comment by timbussmann** [comment]
@Particular/nservicebus-maintainers @mikeminutillo please review

**Comment by andreasohlund** [comment]
:+1:

**Comment by andreasohlund** [comment]
@janovesk is the gateway/distributor reading this setting by any chance?

**Comment by janovesk** [comment]
As a endpoint the distributor reads it of course, but distirbutor is going away, so no problem there. 

Gateway has its own maxConcurrency settings, but those are defined per channel. There is an [issue](https://github.com/Particular/NServiceBus.Gateway/issues/27) for going code first there as well.

**Comment by andreasohlund** [comment]
:+1:

**Pull request merged**
