### PR TITLE
[WIP] use ILRepack instead of ILMerge

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by timbussmann** [comment]
@SimonCropp given the conversation on the pdev issue, is there any value in switching to ILRepack atm?

**Comment by bording** [comment]
After talking with the rest of the maintainers today, we've decided to hold off on merging this PR for now. We'd like to wait to make this change until we find that it is actually needed.

It's possible that ILMerge could get proper portable PDB support before ILRepack, so we'd then just need to change back again.

**Comment by SimonCropp** [comment]
@bording given our recent conversation about removing the ilmerged bits, should we kill this one?

**Comment by bording** [comment]
@SimonCropp Yeah, not much point in keeping this around now that we've decided to remove the dependencies.

**Pull request closed without merging**
