### PR TITLE
Adding JetBrains Rider (.NET IDE) specific files to .gitignore

### PR DESCRIPTION
**Pull request by hmemcpy**

### CODE REVIEW

**Comment by SimonCropp** [comment]
@hmemcpy can u add it here instead for global approval/discussion. https://github.com/Particular/RepoStandards/blob/master/.gitignore

**Comment by hmemcpy** [comment]
Sure thing @SimonCropp!

**Comment by SimonCropp** [comment]
cant think any any reason for people will object. if no one does we will raise an issue that links to all repos and use syncomatic to push it everywhere. sound ok?

**Comment by hmemcpy** [comment]
Sounds excellent! :+1:

**Pull request merged**
