### PR TITLE
[WIP]Sending pre-created interface message fails

### PR DESCRIPTION
**Pull request by andreasohlund**
I have a customer upgrading from v5 to v7 and in v7 we only provide a `Send<T>` overload that take an action to create interface messages. This means that if you use the plain send to send the message routing will fail since we're looking for the route that matches `.GetType` which gives the autogenerated `impl` class.

This PR shows a repro and results in:

```
No destination specified for message: NServiceBus.AcceptanceTests.Core.Routing.When_routing_interface_message\\+IMyMessage__impl
```

One could argue that the user should change their code to use the mentioned action overload but since we still expose the message creator it feels wrong that it doesn't work?

### CODE REVIEW

**Comment by andreasohlund** [comment]
Not confirmed but looking at the code the fix would be to put the `<T>` back on the plain send which would require a minor

Another alternative would be to make the routing smarter and fall back to check for implemented interfaces as well when looking for routes but I have a hunch there would be plenty of dragons there

**Comment by bording** [comment]
Seems like there should be a place to add a call to the mapper in there to get back the correct interface type?

**Comment by andreasohlund** [comment]
>Seems like there should be a place to add a call to the mapper in there to get back the correct interface type?

Good point, that actually fixes it 👍

**Comment by andreasohlund** [comment]
Pushed a test that checks if we need to apply the same change to the `Publish` counterpart but so far it passes since:

* [LearningTransport check all implemented interfaces](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Transports/Learning/LearningTransportDispatcher.cs#L183)
* [MessageDriven pub sub looks at the message inheritance hierachy as well](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Routing/UnicastPublishRouter.cs#L25)
* Rabbit: TBD
* Old ASB: TBD
* New ASB: TBD

**Comment by andreasohlund** [comment]
That said the `impl` is passed as the event type to the routing pipeline part so I could imagine this causing issues for user implementing their own routing extensions?

https://github.com/Particular/NServiceBus/pull/5359/files#diff-9f55b01bc714e0cfd0b2e61633e0ad93R32

**Comment by andreasohlund** [comment]
Rabbit also works since it looks at the inheritance hierarchy 

https://github.com/Particular/NServiceBus.RabbitMQ/blob/develop/src/NServiceBus.Transport.RabbitMQ/Routing/ConventionalRoutingTopology.cs#L111

Just realized that all native pubsub transports needs to do this in order to support message inheritance in general so there is no message loss scenario here.

So the question is if we want to change pubsub so that the correct event type is available in the pipeline?

Ie to make https://github.com/Particular/NServiceBus/pull/5359/files#diff-9f55b01bc714e0cfd0b2e61633e0ad93R32 pass.

**Comment by bording** [comment]
@andreasohlund Do you think we could change how we're getting access to the mapper here? Seems like a decent amount of overhead to be calling into the builder for each send.

**Comment by bording** [comment]
> So the question is if we want to change pubsub so that the correct event type is available in the pipeline?

It's not clear to me what you're saying the current behavior is that we'd be changing?

**Comment by andreasohlund** [comment]
>It's not clear to me what you're saying the current behaviour is that we'd be changing?

Without https://github.com/Particular/NServiceBus/pull/5359/files#diff-59e8e774c2bd8041f702a3a0f23d4de2R21 the message type available in the pipeline via eg. https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Pipeline/Outgoing/OutgoingLogicalMessage.cs#L26 would be `MyEvent__impl` and https://github.com/Particular/NServiceBus/pull/5359/files#diff-9f55b01bc714e0cfd0b2e61633e0ad93R32 would fail.

Even though pubsub kind of works since we look for inherited messages when resolving subscribers I think passing the correct type is the right thing to do?

**Comment by andreasohlund** [comment]
Replaced by https://github.com/Particular/NServiceBus/pull/5363

**Pull request closed without merging**
