### PR TITLE
RegisterPublisherFor* methods replaced with simple RegisterPublisher

### PR DESCRIPTION
**Pull request by Scooletz**
Connects to https://github.com/Particular/V6Launch/issues/68

### CODE REVIEW

**Comment by Scooletz** [comment]
Ping @timbussmann

**Comment by danielmarbach** [comment]
Looks good from my side. Since I do not have the context of the TF I will not merge until @timbussmann chimes in

**Comment by bording** [comment]
Making these overloads instead of separate methods aligns with the approach we took for `RouteToEndpoint`, and we had discussed doing the same thing here, so :+1:

@Scooletz Looking at the name of the Assembly parameter compared to the equivalent parameter on the `RouteToEndpoint` methods, I wonder if it would be preferable to align the names, and make it just be `assembly` here as well.

I'd also argue that we could drop "message/event" from the namespace parameter.

Probably worth keeping the destination/publisherEndpoint distinction though.

**Comment by Scooletz** [comment]
@bording Will apply.

**Comment by timbussmann** [comment]
Looks good to me. :+1: to @bording suggestions. @Scooletz ping me when you applied them, so we can merge this :tada:

**Comment by Scooletz** [comment]
@timbussmann ping

**Comment by timbussmann** [comment]
now this would be a good time to ping @Particular/azure-service-bus-maintainers to align their API with this. @Scooletz are you interested in raising a PR for that?

**Comment by Scooletz** [comment]
@timbussmann Will do.

**Pull request merged**
