### PR TITLE
update obsoleteEx

### PR DESCRIPTION
**Pull request by SimonCropp**
Connects to https://github.com/Particular/PlatformDevelopment/issues/706

### CODE REVIEW

**Comment by SimonCropp** [comment]
@ramonsmits as discussed makes better use of not implemented exceptions. config settings are here 

https://github.com/Fody/Obsolete#throwsnotimplementedtext https://github.com/Fody/Obsolete#removeinversionformat

**Comment by danielmarbach** [comment]
So if it is a concrete type with members then the members mention the `NotImplementedException`?

**Comment by SimonCropp** [comment]
not exactly. it actually looks for a `throw new NotImplementedException()`

**Comment by timbussmann** [comment]
:+1:

**Comment by andreasohlund** [comment]
:+1:

**Comment by danielmarbach** [comment]
Ah nice!

**Pull request merged**
