### PR TITLE
Consistently using RuntimeEnvironment class to get the current machine name

### PR DESCRIPTION
**Pull request by SzymonPobiega**

### CODE REVIEW

**Comment by SimonCropp** [comment]
how expensive is getting the machine name?

**Comment by SzymonPobiega** [comment]
@SimonCropp not sure, didn't check that. But this PR does not change it because `RuntimeEnvironment` delegates to `Environment`.

**Comment by bording** [comment]
> how expensive is getting the machine name?

I know it can be pretty expensive, because I saw that method taking up a good bit of time when I was profiling. That's what led to #3710.

@SzymonPobiega Looking at the remaining uses, I can see that `Environment.MachineName` is still used in some tests. Should those be changed too?

**Comment by SzymonPobiega** [comment]
@bording I changed also the usages in the tests.

**Comment by danielmarbach** [comment]
It is good that we make it consistent. I'm just wondering how we deal with it when we potentially implement https://github.com/Particular/NServiceBus/issues/3845

**Comment by timbussmann** [comment]
The changes seem to make a lot of sense to me :+1: 

I don't mind about #3845 for now @danielmarbach

**Comment by bording** [comment]
Regardless of the other changes we might decide on (#3845, #3846), it still makes sense to have these changes in place first.

I'm going to go ahead and merge this.

**Pull request merged**
