### PR TITLE
[WIP] Remove SynchronizedStorageSession Cast and missing 'I'

### PR DESCRIPTION
**Pull request by colin-higgins**
Add Enlist method to interface to remove cast. Add 'I' to interfaces.

I see that `SynchronizedStorageSession` is on the handler context and that it's difficult to choose precise methods for managing pieces of work in transactions across many different technologies. Casting just doesn't seem to be the way to go. Unless it really will be limited to the in memory option.

@SimonCropp @danielmarbach @SzymonPobiega @bording

### CODE REVIEW

**Comment by SzymonPobiega** [comment]
@colin-higgins the storage session has intentionally been empty. The enlist method makes sense for an in-memory one but it does not make sense for NHibernate (wrapper around `ISession`) or RavenDB. The idea behind SSS was to make core aware of the concept and able to control the lifetime but the core should not assume anything about SSS. The fact that it was downcasted was intentional. 

Although I agree that for cosistency reasons we might add `I`. I based my name on @andreasohlund 's `OutboxTransaction` which is another empty interface.

**Comment by danielmarbach** [comment]
I seriously don't understand the cargo culting around the I. We are
oppinionated about namespaces, async postfixes... But not around I

On Monday, December 7, 2015, Szymon Pobiega <notifications@github.com>
wrote:

> @colin-higgins <https://github.com/colin-higgins> the storage session has
> intentionally been empty. The enlist method makes sense for an in-memory
> one but it does not make sense for NHibernate (wrapper around ISession)
> or RavenDB. The idea behind SSS was to make core aware of the concept and
> able to control the lifetime but the core should not assume anything about
> SSS. The fact that it was downcasted was intentional.
>
> Although I agree that for cosistency reasons we might add I. I based my
> name on @andreasohlund <https://github.com/andreasohlund> 's
> OutboxTransaction which is another empty interface.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/NServiceBus/pull/3170#issuecomment-162444631>
> .
>


-- 
*#NSBcon 2015 • The "All About NServiceBus" conference is back *
*• Learn more <http://go.particular.net/l/27442/2015-08-21/5d4wzp> →*

**Comment by SimonCropp** [comment]
@danielmarbach yes we are opinionated about namespaces and postfix. And we have rules about them. And we can consistently follow those rules.

I broight up the I thing since i saw no reason for the inconsistency. If u can articulate the rules of when to prefix an interface and when not to we wont need to cargo cult it.

**Comment by danielmarbach** [comment]
How about:

* Extension points meant to be implemented by endusers (often scanned, or
by convention) are prefixed with I
* infrastructure extensions mostly (if ever) only used by customers rarely
ever implemented have no I prefix

?


-- 
*#NSBcon 2015 • The "All About NServiceBus" conference is back *
*• Learn more <http://go.particular.net/l/27442/2015-08-21/5d4wzp> →*

**Comment by timbussmann** [comment]
Does `ISynchronizedStorageSession` really need to be available on the `IMessageHandlerContext`?

**Comment by SzymonPobiega** [comment]
@timbussmann it should be used to access the data in the handler so I'd say yes because that's the essence of most message handlers.

**Comment by colin-higgins** [comment]
@danielmarbach 
The `I` question is not of cargo cult. Labeling an opinion as cargo cult seems unproductive here.
Why do we focus so much on naming things? What is the goal? It's to make things more clear and to reduce cognitive overhead.
If keeping the standard to have an `I` on interfaces makes it easier for folk with less brain power like me, why would we bother maintaining several rule sets in our head? Does removing the `I` add any value?

@SzymonPobiega So you're saying this will be the only time we cast it? If so, what is the point of passing  the `ISynchronizedStorageSession` to every single persistence implementation? Especially if it has no methods. What is the point of exposing it on `IMessageHandlerContext` if it has no methods?

**Comment by danielmarbach** [comment]
Unproductive. Let's discuss it over a call, I learned from the past I won't
comment this here.

On Monday, December 7, 2015, Colin Higgins <notifications@github.com> wrote:

> @danielmarbach <https://github.com/danielmarbach>
> The I question is not of cargo cult. Labeling an opinion as cargo cult
> seems unproductive here.
> Why do we focus so much on naming things? What is the goal? It's to make
> things more clear and to reduce cognitive overhead.
> If keeping the standard to have an I on interfaces makes it easier for
> folk with less brain power like me, why would we bother maintaining several
> rule sets in our head? Does removing the I add any value?
>
> @SzymonPobiega <https://github.com/SzymonPobiega> So you're saying this
> will be the only time we cast it? If so, what is the point of passing the
> ISynchronizedStorageSession to every single persistence implementation?
> Especially if it has no methods. What is the point of exposing it on
> IMessageHandlerContext if it has no methods?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/NServiceBus/pull/3170#issuecomment-162562027>
> .
>


-- 
*#NSBcon 2015 • The "All About NServiceBus" conference is back *
*• Learn more <http://go.particular.net/l/27442/2015-08-21/5d4wzp> →*

**Comment by timbussmann** [comment]
@colin-higgins I had a quick chat with @SzymonPobiega about the transaction classes. Here's his idea he gave me which may help you too:

```
public class MyHandler
{
   public void Handle(MyMessage msg, IMessageHandlingContext ctx)
   {
      ctx.StorageSession.RavenDB().Store(new SomeDocument(msg.Data));
   }
}
```

I think it shows why an `Enlist` itself won't work with specific storage sessions.

**Comment by colin-higgins** [comment]
@timbussmann @SzymonPobiega 
How about: 
```
public class MyHandler
{
   public void Handle(MyMessage msg, IMessageHandlingContext ctx)
   {
      ctx.Enlist<RavenDB>(storage => storage.Store(new SomeDocument(msg.Data)));
   }
}
```

**Comment by SzymonPobiega** [comment]
@colin-higgins Enlist would not give us anything. The point of having this storage session is to be able to control the lifetime in code (hence no methods) but be able to use the implementation-specific stuff in the concrete persistence repos. I think when the NHibernate peristence is done it will be more clear because not all the implementations of a storage session are more-or-less degenerate.

**Comment by danielmarbach** [comment]
Furthermore the strong typing of the API happens on the persister specific
API which also needs to support async API. Lifting it up to a generic
enlist would not help

On Tuesday, December 8, 2015, Szymon Pobiega <notifications@github.com>
wrote:

> @colin-higgins <https://github.com/colin-higgins> Enlist would not give
> us anything. The point of having this storage session is to be able to
> control the lifetime in code (hence no methods) but be able to use the
> implementation-specific stuff in the concrete persistence repos. I think
> when the NHibernate peristence is done it will be more clear because not
> all the implementations of a storage session are more-or-less degenerate.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/NServiceBus/pull/3170#issuecomment-162809317>
> .
>


-- 
*#NSBcon 2015 • The "All About NServiceBus" conference is back *
*• Learn more <http://go.particular.net/l/27442/2015-08-21/5d4wzp> →*

**Comment by colin-higgins** [comment]
@szymonpobiega I understand. It just seems like a design smell to pass something that won't be used to every implementation.

@danielmarbach the enlist can easily be converted to async. I've done so locally.

**Comment by andreasohlund** [comment]
@colin-higgins @SzymonPobiega did you guys agree on the next steps?

**Comment by andreasohlund** [comment]
Ping @colin-higgins @SzymonPobiega

**Comment by colin-higgins** [comment]
I think all that is left is closing this. It sounds like we are establishing a convention for including I on interfaces and that we've chosen casting.

**Pull request closed without merging**
