### PR TITLE
Update to .NET 4.5.1 and support thread change operations inside handlers.

### PR DESCRIPTION
**Pull request by Thorium**
We had a huge issue that when we use async-await operations inside handlers (while they did have explicit .Wait() there is still possibility to thread to change). Now, if thread changed, the other thread didn't had DTC-transaction enabled (because .NET 4.5 old DTC didn't support this), causing deadlocks (in Oracle database queries).

So this fix won't enable asnyc-await handlers, it just fixes the deadlocks that may happen if there is any async-await-code that is manually waited inside a handler. Which there might be, e.g. due to code-reuse or some other reason.

### CODE REVIEW

**Comment by finbaystone** [comment]
+1

**Comment by Thorium** [comment]
Fix for issue #2674

**Comment by Thorium** [comment]
I can't access the CI server to see why the build failed. Maybe CI doesn't have .NET 4.5.1 installed?

**Comment by johnsimons** [comment]
@Thorium I'll raise this internally and see where it takes us

**Comment by johnsimons** [comment]
@Thorium we haven't been able to replicate #2674, can you help us replicate the issue you are experiencing so we can cover it with tests ?

**Comment by Thorium** [comment]
I wasn't able to reproduce the issue with a small test application in about an hour.

But actually setting this TransactionScopeAsyncFlowOption to Enabled (which is a 4.5.1 feature) to transactionscope constructor was fixing the problem. And I don't see that it could have any negative side-effects in your source code.

**Comment by danielmarbach** [comment]
@Thorium Thanks again for your PR. Awesome job! I incorporated your commit on this PR https://github.com/Particular/NServiceBus/pull/2770 I'm going to close this one here.

**Comment by Thorium** [comment]
Thanks Daniel! Hope to get this new version from NuGet soon.

**Pull request closed without merging**
