### PR TITLE
Move mandatory settings to ctor

### PR DESCRIPTION
**Pull request by mauroservienti**

### CODE REVIEW

**Comment by mauroservienti** [comment]
Not sure how to handle this case though: https://github.com/Particular/NServiceBus/blob/mandatory-properties/src/NServiceBus.AcceptanceTesting/AcceptanceTestingTransport/AcceptanceTestingTransportInfrastructure.cs#L65

**Comment by timbussmann** [comment]
> Not sure how to handle this case though: https://github.com/Particular/NServiceBus/blob/mandatory-properties/src/NServiceBus.AcceptanceTesting/AcceptanceTestingTransport/AcceptanceTestingTransportInfrastructure.cs#L65

I think that `EnablePublishSubscribe` can be directly replaced with the `SupportsPublishSubscribe`?

**Comment by mauroservienti** [comment]
it means it needs to be get/set in the base class, which makes only sense for the AcceptanceTestingTransport, or am I missing something?

**Review by tmasternak — APPROVED** [review]

**Comment by mauroservienti** [comment]
I should have fixed all the places where this is used in Core. @SzymonPobiega @timbussmann @tmasternak please review.

**Review by timbussmann — APPROVED** [review]

**Pull request merged**
