### PR TITLE
Fix timeout dispatching for v6

### PR DESCRIPTION
**Pull request by timbussmann**
Connects to #2885

### CODE REVIEW

**Comment by timbussmann** [comment]
@andreasohlund @weralabaj @Particular/nservicebus please review

**Comment by weralabaj** [comment]
I guess there is some discussion behind removing HandleBackwardsCompatibility, can you provide background?

**Comment by andreasohlund** [comment]
>I guess there is some discussion behind removing HandleBackwardsCompatibility, can you provide background?

It was there to support side by side upgrade btw v2.6 and 3.0 so I think its fair to say that it can be removed since side by side upgrades btw 2.6 and 6.0 is highly unlikely/not supported (we recommend users to go major to major +1 )

**Comment by weralabaj** [comment]
And we still have it in 5, interesting ;)

**Comment by andreasohlund** [comment]
Better safe than sorry :)

**Comment by andreasohlund** [comment]
@Particular/tf-asyncawait please review

**Comment by timbussmann** [comment]
good to merge then?

**Pull request merged**
