### PR TITLE
[WIP][DO NOT MERGE] Dispatch diagnostic tracing

### PR DESCRIPTION
**Pull request by DavidBoike**
Just creating a build with diagnostic tracing for a customer having an issue.

Maintainers please ignore.

### CODE REVIEW

**Comment by boblangley** [comment]
I think some logging should be added here as well. It would be nice to know where in the ReceiveMessage we reach.

https://github.com/Particular/NServiceBus/blob/dont-merge-dispatch-tracing/src/NServiceBus.Core/Transports/Msmq/ReceiveOnlyNativeTransactionStrategy.cs

**Comment by bording** [comment]
@DavidBoike @boblangley Do you still need this?

**Comment by DavidBoike** [comment]
@bording Yes. Will close the PR and delete the branch when I'm done.

**Comment by DavidBoike** [comment]
Customer resolved their issue by having non-zero value for connect timeout in their connection string. The zero value triggers a bug in the SQL client when connecting to mirrored databases.

SQL client bug with respect to mirroring is described here:

https://social.msdn.microsoft.com/Forums/vstudio/en-US/a9709e71-2748-4120-b16d-2fdd489c9e75/entity-framework-breaks-when-connecting-to-a-mirrored-sql-server-environment?forum=adodotnetentityframework

**Pull request closed without merging**
