### PR TITLE
remove value tuple

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by danielmarbach** [comment]
This is great. I had huge assembly redirect problems today because of ValueTuple. See

https://github.com/dotnet/standard/issues/476
https://github.com/SixLabors/ImageSharp/issues/270

and many more

**Comment by danielmarbach** [comment]
What is interesting is the following, although I added

```
        var scanner = configuration.AssemblyScanner();
        scanner.ExcludeAssemblies("System.ValueTuple.dll");
```

and 

```
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.ValueTuple" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.2.0" newVersion="4.0.2.0" />
      </dependentAssembly>
    </assemblyBinding>
```

it is still failing with a BadImageFormatException

```
   at NServiceBus.Hosting.Helpers.AssemblyScanner.TryLoadScannableAssembly(String assemblyPath, AssemblyScannerResults results, Assembly& assembly)
   at NServiceBus.Hosting.Helpers.AssemblyScanner.GetScannableAssemblies()
   at NServiceBus.EndpointConfiguration.GetAllowedTypes(String path)
   at NServiceBus.EndpointConfiguration.Build()
   at NServiceBus.Endpoint.Create(EndpointConfiguration configuration)
   at NServiceBus.Endpoint.<Start>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at WorkerRole.<StartEndpoint>d__3.MoveNext() in C:\p\docs.particular.net\samples\azure\self-host\Core_7\HostWorker\WorkerRole.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at WorkerRole.OnStart() in C:\p\docs.particular.net\samples\azure\self-host\Core_7\HostWorker\WorkerRole.cs:line 17
   at Microsoft.WindowsAzure.ServiceRuntime.RoleEnvironment.InitializeRoleInternal(RoleType roleTypeEnum)
   at Microsoft.WindowsAzure.ServiceRuntime.Implementation.Loader.RoleRuntimeBridge.<InitializeRole>b__0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by danielmarbach** [comment]
As an FYI it turned out the problem manifestation is a combination of `Microsoft.WindowsAzure.targets` with old csproj using `PackageReference` with a ref assembly. More details can be found https://github.com/Azure/azure-sdk-for-net/issues/3699

**Comment by andreasohlund** [comment]
Even though it was a problem with the azure target this highlights that this can cause issues that we can't forsee. Given that this has no external impact and we can start using it as soon as we bump to net471 (?) I'd say the risk isn't worth it.

Lets get this in

**Comment by dbelcham** [comment]
@SimonCropp we're looking at making this change, but we need this PR to compile and pass tests first.

**Comment by SimonCropp** [comment]
build is fixed. please merge

**Comment by andreasohlund** [comment]
I will remove the upgrade note about this

**Pull request merged**
