### PR TITLE
add naming convention

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by SimonCropp** [comment]
@andreasohlund as discussed

**Comment by andreasohlund** [comment]
:+1: @Particular/nservicebus what do you think?

Essentially this means:

Namespaces are optimised for external users

* Public api that end users should care about: `NServiceBus`
* Public api that extension developers should care about `NServiceBus.{extension type}`
   - Transports
   - Persitence
   - Serializers
   - Containers
   - etc

Folders are optimized for us organizing the code into "feature folders"
* All non public types goes into the `NServiceBus` namespace to give a nice stacktrace and allow users to filter logging on `NServiceBus`
* Given this we can rename folders without having to worry about adjusting namespaces

To find vierd dependencies just to a find usages and look for multiple top level folders. Eg. we have a bad dependency where the satellites are reusing the flr and error queue behaviors. This can be seen here:

bad-flr-dep

Notice the delayed delivery satellites depending on the flr behavior

**Comment by danielmarbach** [comment]
:+1:

On Wednesday, December 2, 2015, Andreas Öhlund <notifications@github.com>
wrote:

> [image: :+1:] @Particular/nservicebus
> <https://github.com/orgs/Particular/teams/nservicebus> what do you think?
>
> Essentially this means:
>
> Namespaces are optimised for external users
>
>    - Public api that end users should care about: NServiceBus
>    - Public api that extension developers should care about NServiceBus.{extension
>    type}
>       - Transports
>       - Persitence
>       - Serializers
>       - Containers
>       - etc
>
> Folders are optimized for us organizing the code into "feature folders"
>
>    - All non public types goes into the NServiceBus namespace to give a
>    nice stacktrace and allow users to filter logging on NServiceBus
>    - Given this we can rename folders without having to worry about
>    adjusting namespaces
>
> To find vierd dependencies just to a find usages and look for multiple top
> level folders. Eg. we have a bad dependency where the satellites are
> reusing the flr and error queue behaviors. This can be seen here:
>
> [image: bad-flr-dep]
> <https://cloud.githubusercontent.com/assets/125028/11550759/61c2f2d0-9938-11e5-8bcd-f0952a7d4c96.PNG>
>
> Notice the delayed delivery satellites depending on the flr behavior
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/NServiceBus/pull/3162#issuecomment-161502500>
> .
>


-- 
*#NSBcon 2015 • The "All About NServiceBus" conference is back *
*• Learn more <http://go.particular.net/l/27442/2015-08-21/5d4wzp> →*

**Comment by tmasternak** [comment]
:+1:

BTW. How many name collisions did we get when doing those changes?

**Comment by SimonCropp** [comment]
@tmasternak one. to do with the xml Serializer being named "Serializer"

**Comment by SimonCropp** [comment]
@timbussmann @danielmarbach @janovesk @SzymonPobiega 

so will this cause any friction for branches you have? need me to hold off and re-apply on top your merged changes?

**Comment by janovesk** [comment]
I closed some and the rest we can rebase. Objections @SzymonPobiega?

**Comment by timbussmann** [comment]
@SimonCropp yes I think that could be a major issue for my "interfaces" PR. Would be great if we could pull that in first.

Thanks for summarizing the changes @andreasohlund

**Comment by andreasohlund** [comment]
>to do with the xml Serializer being named "Serializer"

Another benefit: Forces us to name things properly :) (I wouldn't be supprised if it was me who created that "Serializer" class

**Comment by SimonCropp** [comment]
@timbussmann ok. can u let me know when i can re-apply and merge?

**Comment by timbussmann** [comment]
@SimonCropp will do, thanks :+1:

**Comment by timbussmann** [comment]
@SimonCropp good to go. Thanks for waiting!

**Comment by andreasohlund** [comment]
@SimonCropp rebase so we can pull this?

**Comment by SimonCropp** [comment]
replaced by https://github.com/Particular/NServiceBus/pull/3218

**Pull request closed without merging**
