### PR TITLE
better subscription Authorizer

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by SimonCropp** [comment]
@andreasohlund @SzymonPobiega review please

**Comment by SzymonPobiega** [comment]
So we now use a delegate instead of registering an interface implementation in the container. I like this approach more. Should we somehow make it more visible that we are going in that direction? I think @andreasohlund also wanted to have similar approach to some of the callback interfaces used during the init and start-up phases.

**Comment by andreasohlund** [comment]
> I think @andreasohlund also wanted to have similar approach to some of the callback interfaces used during the init and start-up phases.

:+1:

**Comment by SzymonPobiega** [comment]
It this something we want to publicly discuss first? This seems like a major change in our extensibility story and, although I agree, I wonder if we should get everybody aligned/on board?

**Comment by SimonCropp** [comment]
@SzymonPobiega this is the same approach used for the msmq label http://docs.particular.net/nservicebus/msmq/transportconfig#configuration-msmq-label

**Comment by SzymonPobiega** [comment]
Cool. Let's merge it and make sure we communicate that internally.

**Pull request merged**
