### PR TITLE
[Spike] Reduced replaceable unicast pubsub

### PR DESCRIPTION
**Pull request by Scooletz**
Based on #4287

This PR limits the interface for any implementor willing to provide a custom provider for pub sub routing.
It does by:
- introducing `IUnicastPublishProvider` introduced as a contract providing  `IUnicastPublish`
- making `AutoSubscribe` & `MessageDrivenSubscriptions` dependent on NOT having a `IUnicastPublishProvider` registered
- introducing `ExternalSubscribe` which wires in `IUnicastPublishProvider`

This approach limits the interface of `IUnicastPublish` only to providing routes, removing uneeded Subscribe/Unscubsribe methods.

### CODE REVIEW

**Comment by Scooletz** [comment]
Ping @timbussmann

**Comment by Scooletz** [comment]
@timbussmann I pushed the recent commit as a kind of notes after our discussion about this approach:
- `Settings` vs `Container` in the preprequistes
- keeping the provider/factory

**Comment by timbussmann** [comment]
@Scooletz how do you want to proceed with this spike? Can we close it or do you want to somehow move further with this?

**Comment by Scooletz** [comment]
This was just a spike and pushed our discussion forward. I'm closing it @timbussmann

**Pull request closed without merging**
