### PR TITLE
Added logging when PurgeOnStartup is performed

### PR DESCRIPTION
**Pull request by dbelcham**
Addresses #4410 

Added WARN level logging when a queue is purged that reads:
> The {QueueName} queue was purged.

### CODE REVIEW

**Comment by andreasohlund** [comment]
Should we add similar log statements to the other transports? Or move the statement one level up?

"WARN-Requesting transport to purge {queue name}"?

**Comment by danielmarbach** [comment]
@andreasohlund we could also do it in a transport agnostic way. So for example we log it when you call `PurgeOnStartup `in the `ConfigurePurging` class. With that we wouldn't need to log it in each transport. Thoughts?

**Comment by danielmarbach** [comment]
@andreasohlund talked to @dbelcham we are going to move it into the startable endpoint

**Comment by dbelcham** [comment]
Please squash when merging

**Pull request merged**
