### PR TITLE
Made routing-related types public.

### PR DESCRIPTION
**Pull request by SzymonPobiega**
Following types/methods has been made public:
 * `DistributionPolicy`
 * `UnicastRouter` and `IUnicastRouter`
 * `GetDestinationsFor()` in `UnicastRoutingTable`

These changes are necessary making custom routing scenario work. `DistributionPolicy` and `UnicastRouter` implement core routing logic without which it would be very hard to implement a custom routing behavior (such as `UnicastPublishRouterConnector`). By very hard I mean massive copy-paste of NServiceBus core routing code. Here's a class that is essential for custom routing that depends on these things being public:

```
class CustomPublishRouter : UnicastRouter
{
    public CustomPublishRouter(UnicastRoutingTable unicastRoutingTable, MessageMetadataRegistry messageMetadataRegistry, EndpointInstances endpointInstances, TransportAddresses physicalAddresses) 
        : base(messageMetadataRegistry, endpointInstances, physicalAddresses)
    {
        this.unicastRoutingTable = unicastRoutingTable;
    }

    protected override Task<IEnumerable<IUnicastRoute>> GetDestinations(ContextBag contextBag, List<Type> typesToRoute)
    {
        return unicastRoutingTable.GetDestinationsFor(typesToRoute, contextBag);
    }

    UnicastRoutingTable unicastRoutingTable;
}
```

### CODE REVIEW

**Comment by SzymonPobiega** [comment]
@Particular/nservicebus-maintainers please review.

**Comment by timbussmann** [comment]
can you please update the description to give a short overview of the changes and the usage scenarios of the new API (e.g. the benefits)?

**Comment by SzymonPobiega** [comment]
@timbussmann I updated the description.

**Comment by timbussmann** [comment]
> These changes are necessary making custom routing scenario work.

is this something we really want to support with v6.0? What would the scenario be with custom routing, was this possible in v5 and if yes, who was using this?

**Comment by SzymonPobiega** [comment]
@timbussmann similar thing in V5 was achievable by providing custom config provider with the MEMappings but not to the same degree as in V6. I discovered that these types are missing while building a custom routing sample.

**Comment by SzymonPobiega** [comment]
@timbussmann please hold on with that, I'll make sure I can't achieve the same thing in other ways. WIll ping you here soon.

**Comment by SzymonPobiega** [comment]
@timbussmann I did check and it would be hard. I definitely need `DistributionPolicy` because every non-trivial routing customization has to involve distribution. Without `UnicastRouter` I can live but I'll have to copy-paste it to the sample.

**Comment by timbussmann** [comment]
> I discovered that these types are missing while building a custom routing sample.

can't we just have a sampe which makes use of the dynamic routing rules instead of replacing everything?

**Comment by SzymonPobiega** [comment]
I think the value is bigger than the cost of making these types public. They have well-defined contract and it is unlikely that we'll have to change them in the V6 era.

**Comment by SzymonPobiega** [comment]
@timbussmann I managed to refactor the sample to not use these types. Closing.

**Pull request closed without merging**
