### PR TITLE
Make pipelines explicit

### PR DESCRIPTION
**Pull request by SzymonPobiega**
This pull makes `PipelineBase<>` an abstract class forcing creating an explicit type for each pipeline. Each such pipeline is registered in the container so that we can avoid creating pipelines in place.

Another change is that the behavior contexts do not directly implement `IMessageHandlingContext` and `IMessageProcessingContext` so that when a behavior wants to use a pipeline, it needs to explicitly depend on proper `IPipeInlet<T>`. This change allows us to generate nice pipeline graphs like this one:

the pipeline 2

### CODE REVIEW

**Comment by SzymonPobiega** [comment]
@andreasohlund @danielmarbach @timbussmann @Particular/nservicebus please review

**Comment by danielmarbach** [comment]
@SzymonPobiega can we get on a call next week? I have a few questions I would like to discuss. I think it is an interesting idea to explore but not yet really convinced about the removal of the bus operations on the contexts

**Comment by SzymonPobiega** [comment]
Any time you want @danielmarbach :)

**Comment by timbussmann** [comment]
I have to agree with @danielmarbach. It's an interesting change, especially when considering my spikes about making the context more testable. I have not yet made a real opinion but things I noted:
* `IPipeInlet<T>` is a "complicated" naming and difficult to explore. We should provide `ISendPipeline` etc. 
* `IPipeInlet<T>` would easily allow to test bus operations, possibly reducing effort on making contexts more testable
* I don't think having this graphic offers enough value to change the design significantly (just as the single justification)
* It does separate concerns on the context (data vs. operations).
* It's not as nice to use as `context.Send` and so on.
* Couples us more to DI (also user code needs to inject NSB components together with his custom services again).

I'd like to join that discussion.

**Comment by danielmarbach** [comment]
@andreasohlund @SzymonPobiega @timbussmann can we hash this out this week or after the conference?

**Comment by andreasohlund** [comment]
Think we need to get on a quick call and discuss?

**Comment by danielmarbach** [comment]
Exactly my point

**Comment by andreasohlund** [comment]
Glad I could help by beeing: 

 http://www.tegile.com/wp-content/uploads/2015/08/captain-obvious-south-park.jpg

:)

**Comment by SzymonPobiega** [comment]
Today after the sync?

**Comment by danielmarbach** [comment]
Better tomorrow

On Tuesday, November 24, 2015, Szymon Pobiega <notifications@github.com>
wrote:

> Today after the sync?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/NServiceBus/pull/3099#issuecomment-159186413>
> .
>


-- 
*#NSBcon 2015 • The "All About NServiceBus" conference is back *
*• Learn more <http://go.particular.net/l/27442/2015-08-21/5d4wzp> →*

**Comment by SzymonPobiega** [comment]
@danielmarbach it's all yours!

**Comment by danielmarbach** [comment]
Thanks @SzymonPobiega 

I started working on it today. Still sorting out a few things in the current pipeline to better understand it. For example see #3233

**Comment by danielmarbach** [comment]
Potentially superseeded by #3262

**Comment by danielmarbach** [comment]
Superseeded by https://github.com/Particular/NServiceBus/pull/3262

**Pull request closed without merging**
