### PR TITLE
Stopping pipeline collections concurrently

### PR DESCRIPTION
**Pull request by danielmarbach**
@distantcam rightfully pointed out that I screwed up.

Here is the fixed version.

### CODE REVIEW

**Comment by distantcam** [comment]
This still doesn't run the stops concurrently and if anything just makes it more single-threaded because now the continuation after the await that used to possibly run in a separate thread (because of the `ConfigureAwait(false)`) now also runs on the main thread.

To demonstrate what I mean, here's some code.

    class Program
    {
        static IEndpointInstance endpoint;

        static void Main(string[] args)
        {
            Debug.WriteLine("Main Thread: " + Thread.CurrentThread.ManagedThreadId);

            AsyncPump.Run(Run);
            AsyncPump.Run(Stop);
        }

        static async Task Run()
        {
            var configuration = new EndpointConfiguration();
            configuration.ForwardReceivedMessagesTo("audit");
            configuration.SendFailedMessagesTo("error");
            configuration.UsePersistence<InMemoryPersistence>();

            endpoint = await Endpoint.Start(configuration);

            await endpoint.SendLocal(new MyCommand());
        }

        static Task Stop()
        {
            return endpoint.Stop();
        }
    }

    public class MyCommand : ICommand { }

    public class MyCommandHandler : IHandleMessages<MyCommand>
    {
        public Task Handle(MyCommand message, IMessageHandlerContext context)
        {
            return Task.FromResult(0);
        }
    }

And change the `PipelineCollection.Stop` method to this.

    public Task Stop()
    {
        var pipelineStopTasks = pipelines.Select(pipeline =>
        {
            Debug.WriteLine("Enter context: " + SynchronizationContext.Current?.GetType());
            Debug.WriteLine("Enter thread: " + Thread.CurrentThread.ManagedThreadId);

            Logger.DebugFormat("Stopping {0} pipeline", pipeline.Id);
            var task = pipeline.Stop();

            Debug.WriteLine("Exit Context: " + SynchronizationContext.Current?.GetType());
            Debug.WriteLine("Exit thread: " + Thread.CurrentThread.ManagedThreadId);

            return task;
        });

        return Task.WhenAll(pipelineStopTasks);
    }

AsyncPump from http://blogs.msdn.com/b/pfxteam/archive/2012/02/02/await-synchronizationcontext-and-console-apps-part-3.aspx

When I run this here is my output.

    Main Thread: 8
    Enter context: Sandbox.AsyncPump+SingleThreadSynchronizationContext
    Enter thread: 8
    Exit Context: Sandbox.AsyncPump+SingleThreadSynchronizationContext
    Exit thread: 8
    Enter context: Sandbox.AsyncPump+SingleThreadSynchronizationContext
    Enter thread: 8
    Exit Context: Sandbox.AsyncPump+SingleThreadSynchronizationContext
    Exit thread: 8
    Enter context: Sandbox.AsyncPump+SingleThreadSynchronizationContext
    Enter thread: 8
    Exit Context: Sandbox.AsyncPump+SingleThreadSynchronizationContext
    Exit thread: 8

All running on the same thread. To fix this you need to force the tasks onto new threads.

    var pipelineStopTasks = pipelines.Select(pipeline => Task.Run(() => 

Output

    Main Thread: 9
    Enter context: 
    Enter context: 
    Enter context: 
    Enter thread: 20
    Enter thread: 16
    Enter thread: 21
    Exit Context: 
    Exit thread: 21
    Exit Context: 
    Exit Context: 
    Exit thread: 20
    Exit thread: 16

**Comment by distantcam** [comment]
This makes me wonder if we should put unit tests in place to ensure that the threading is doing what we think it's doing.

**Comment by danielmarbach** [comment]
I'll come up an example to show you that the threading is not what we are looking for here.

**Comment by distantcam** [comment]
Well then the question is, should the stops be concurrent or not? The original issue said they should be, so that's why I flagged the original PR as an error because it wasn't concurrent.

If the stops need to be specifically not concurrent then this PR is ok as is.

**Comment by distantcam** [comment]
From https://github.com/Particular/PlatformDevelopment/blob/master/designprinciples/nservicebus/component-lifecyle.md.md

> Stop operations should be done in parallel if possible/sensible to allow all components to initiate a graceful stop

Is this correct?

**Comment by danielmarbach** [comment]
I think we should reword the design principle to use the word concurrent instead of parallel. I'll send in a PR.

**Comment by distantcam** [comment]
It is also not concurrent. It's single threaded, and the tasks are forced to finish in order on the main thread.

**Comment by distantcam** [comment]
Add this to the `TransportReceiver`, replacing the `Stop` method.

    private static long flag = 0;

    public async Task Stop()
    {
        var localFlag = Interlocked.Exchange(ref flag, 1);

        if (localFlag == 0)
        {
            Debug.WriteLine("Stop Delayed");
            await Task.Delay(1000).ConfigureAwait(false);
        }
        else
        {
            Debug.WriteLine("Stop Not Delayed");
        }

        if (!isStarted)
        {
            return;
        }

        await receiver.Stop().ConfigureAwait(false);

        isStarted = false;
    }

Output

    Main Thread: 9
    Enter context: Sandbox.AsyncPump+SingleThreadSynchronizationContext
    Enter thread: 9
    Stop Delayed
    Exit Context: Sandbox.AsyncPump+SingleThreadSynchronizationContext
    Exit thread: 9
    Enter context: Sandbox.AsyncPump+SingleThreadSynchronizationContext
    Enter thread: 9
    Stop Not Delayed
    Exit Context: Sandbox.AsyncPump+SingleThreadSynchronizationContext
    Exit thread: 9
    Enter context: Sandbox.AsyncPump+SingleThreadSynchronizationContext
    Enter thread: 9
    Stop Not Delayed
    Exit Context: Sandbox.AsyncPump+SingleThreadSynchronizationContext
    Exit thread: 9

**Comment by danielmarbach** [comment]
I think it is purely a wording issue. For me concurrent means

> occurring or existing simultaneously or side by side

http://dictionary.reference.com/browse/concurrent

and then it boils done to Task vs Thread

 > A Task under the Task Parallel Library is a future or promise. A Task is something you want to be done. In contrast, a Thread is one of the many possible workers who might perform that task. By the contract of a Task, we don't know whether it will be scheduled, whether it will be immediately executed, or whether it is already done the moment we declared it. The Task Parallel Library runtime has the built-in smarts to decide whether a task is executed on the thread that created it or if it needs to be scheduled on the worker thread pool or the IO thread pool. Furthermore, just because a thread was working on a given task doesn't mean that thread will execute all the continuations of that task.
This gets even more complex when we start introducing async/await into the equation. Any time you write an await statement, along with your friend ConfigureAwait(false), the thread currently executing the task can yield back and start executing multiple other tasks. When the I/O operation completes, the remainder of the task (the continuation) is again scheduled as a Task on the currently responsible TaskScheduler. The previously responsible thread might pick up that task and continue working on it. 

http://particular.net/blog/the-dangers-of-threadlocal

So just because the tasks get work on by the same thread, doesn't mean they are not concurrent. 

You are a cheeky man @distantcam by introducing the async pump into the game you are essentially override the synchronization context of the console application (which is the ThreadPool by default) with a single threaded sync context. This explains why you are seing mostly the main thread being used. But even then it doesn't matter. One thread with Tasks using async await is perfectly capable of executing multiple dozens of tasks concurrently. Here is the proof

```
class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Main thread: " + Thread.CurrentThread.ManagedThreadId);

            Console.WriteLine("Run with Async Pump ");
            Console.WriteLine();

            AsyncPump.Run(Run);

            Console.WriteLine();
            Console.WriteLine("Run with GetAwaiter().GetResult()");
            Console.WriteLine();

            Run().GetAwaiter().GetResult();

            Console.ReadLine();
        }

        public static async Task Run()
        {
            var stopWatch = new Stopwatch();
            stopWatch.Start();
            Console.WriteLine("Starting sequential ");
            for (int i = 0; i < 4; i++)
            {
                await Stop().ConfigureAwait(false);
            }
            stopWatch.Stop();
            Console.WriteLine("Sequential took " + stopWatch.Elapsed);
            Console.WriteLine();
            stopWatch.Reset();

            stopWatch.Start();
            Console.WriteLine("Starting concurrent with await");
            var concurrentWithAwaitTasks = Enumerable.Range(0, 4).Select(async i =>
            {
                await Stop().ConfigureAwait(false);
            });
            await Task.WhenAll(concurrentWithAwaitTasks).ConfigureAwait(false);
            stopWatch.Stop();
            Console.WriteLine("Concurrent with await took " + stopWatch.Elapsed);
            Console.WriteLine();
            stopWatch.Reset();

            stopWatch.Start();
            Console.WriteLine("Starting concurrent without await");
            var concurrentTasks = Enumerable.Range(0, 4).Select(i => Stop());
            await Task.WhenAll(concurrentTasks).ConfigureAwait(false);
            stopWatch.Stop();
            Console.WriteLine("Concurrent without await took " + stopWatch.Elapsed);
            Console.WriteLine();
            stopWatch.Reset();
        }

        public static async Task Stop()
        {
            Console.WriteLine("Enter thread: " + Thread.CurrentThread.ManagedThreadId);
            await Task.Delay(5000).ConfigureAwait(false);
            Console.WriteLine("Exit thread: " + Thread.CurrentThread.ManagedThreadId);
        }
    }
```

Output

```
Main thread: 8
Run with Async Pump

Starting sequential
Enter thread: 8
Exit thread: 10
Enter thread: 10
Exit thread: 10
Enter thread: 10
Exit thread: 10
Enter thread: 10
Exit thread: 10
Sequential took 00:00:20.0162722

Starting concurrent with await
Enter thread: 10
Enter thread: 10
Enter thread: 10
Enter thread: 10
Exit thread: 10
Exit thread: 10
Exit thread: 11
Exit thread: 13
Concurrent with await took 00:00:05.0267371

Starting concurrent without await
Enter thread: 13
Enter thread: 13
Enter thread: 13
Enter thread: 13
Exit thread: 10
Exit thread: 13
Exit thread: 12
Exit thread: 11
Concurrent without await took 00:00:05.0040196


Run with GetAwaiter().GetResult()

Starting sequential
Enter thread: 8
Exit thread: 10
Enter thread: 10
Exit thread: 10
Enter thread: 10
Exit thread: 10
Enter thread: 10
Exit thread: 10
Sequential took 00:00:20.0119197

Starting concurrent with await
Enter thread: 10
Enter thread: 10
Enter thread: 10
Enter thread: 10
Exit thread: 10
Exit thread: 11
Exit thread: 10
Exit thread: 14
Concurrent with await took 00:00:05.0250880

Starting concurrent without await
Enter thread: 14
Enter thread: 14
Enter thread: 14
Enter thread: 14
Exit thread: 10
Exit thread: 11
Exit thread: 14
Exit thread: 10
Concurrent without await took 00:00:05.0163415
```

Remove the thread from your world view.

**Comment by danielmarbach** [comment]
Closing this works as intended

**Comment by danielmarbach** [comment]
By the way @distantcam thanks for reviewing the async stuff in the core. It is important that multiple people have a look at it. There is always a chance that we got something wrong.

**Comment by danielmarbach** [comment]
Decided to reopen until @distantcam can review it.

**Comment by distantcam** [comment]
Yes the AsyncPump makes a Console app run with a single threaded sync context. It emulates what WPF and MVC does and is useful for testing since deadlocks happen more often in single thread environments.

`ConfigureAwait(false)` causes the sync context to be reset to the default on the continuation, which is why the exits are sometimes happening on different threads from the enters in your example.

Moving the logging lines around got it to a point where I could see the pipeline stopping concurrently. :+1:

**Comment by danielmarbach** [comment]
@distantcam thanks for coming back. Are you OK if I close this issue?

**Comment by distantcam** [comment]
Yes

**Pull request closed without merging**
