### PR TITLE
[WIP] Send options

### PR DESCRIPTION
**Pull request by timbussmann**
Based on the [this Spike](https://github.com/Particular/NServiceBus/pull/3509) and our experiences while updating the testing framework to v6 I wasn't too happy with the current `SendOptions` API for sending messages. Current "pain points" with `SendOptions`:

* It forces us to use extension methods instead of properties (e.g. `options.SetMessageId(...)` instead of `options.MessageId = ...`) to allow downstream repositories add their own options (e.g. `SendToSite`).
* We need a way to retrieve the configured options again. The current "workaround" is to provide "getter extension methods" (e.g. `options.GetMessageId()`) which feels weird and doesn't reed nicely with many options. It also adds a lot of noise to Intellisense.
* It's nearly impossible to "stringify" the configured options with the current approach. This was noticed on the testing update, because we can't easily output configured options of an outgoing message.
* `SendOptions` can easily be reused in multiple send operations. It's quite easy to introduce bugs or undesired behavior this way.
* To share options between `SendOptions` `PublishOptions` and `ReplyOption` it's sometimes required to duplicate certain extension method (e.g. when it's only support for send and publish but not for reply).

The idea: change the signatures from `Send(object message, SendOptions options)` to `Send(object message, params ISendOption[])` (and similar with publish and reply).

Where `ISendOption` instances are provided by dedicated factories like `Defer.By(TimeSpan delay)` or `Defer.To(DateTimeOffset deliveryDate)`, `MessageId.Set(string messageId)` or `Route.ToThisEndpoint()`.

Advantages of this approach:
* It's much easier to properly "stringify" the options and to analyze options on an outgoing messaage.
* Created options are immutable.
* It's easier to scope options because you can implement the corresponding options interface (e.g. `IPublishOption`).
* This is highly subjective but I think it reads better than the extension methods.
* It allows to expose more meaningful data on the option classes usable for inspection & assertions (e.g. `Headers.Key` or `Defer.TimeSpan`).

Disadvantes:
* It's less explorable, since you can't just see all available like options on the `SendOptions` class. I'd argue this is ok since users probably need to read docs about the specific options anyway, also R# is able to show available factory methods, but it doesn't show them by default for me.
* Fluent APIs are not cool anymore. I'd argue this isn't a fluent API and more OOP than the current approach.

From the spike it seems like this shouldn't be difficult to implement since it's pretty simple to shim it using `SendOptions` internally (and the other way round). It would also be possible to release this with a v6 minor version and support both option configuration approaches in parallel. The implementation of this API is very similar to the current `SendOptions` approach but just avoids the public "options bag" class.

Sample from the Spike:

Before:

```
var options = new SendOptions();
options.DelayDeliveryWith(TimeSpan.FromMinutes(15));
options.RouteToThisEndpoint();
options.SetCorrelationId("correlationId");
options.SetMessageId("messageId");
options.SetHeader("header1", "value1");
options.SetHeader("header2", "value2");
options.RouteReplyToThisInstance();
session.Send(new object(), options);
```

After:

```
session.Send(new object(),
  Defer.By(TimeSpan.FromMinutes(15)),
  Route.ToThisEndpoint(),
  CorrelationId.Set("correlationId"),
  MessageId.Set("messageId"),
  Header.Set("header1", "value1"),
  Header.Set("header2", "value2"),
  Reply.ToThisInstance());
```

@Particular/nservicebus-maintainers please give some feedback

### CODE REVIEW

**Comment by andreasohlund** [comment]
I really like it!

**Comment by bording** [comment]
If you wanted to improve the explorability of the API, all of the factory methods could be located inside a single static `Options` class, which would let you do something like:

`Options.Defer.By(TimeSpan.FromMinutes(15))`

And if you don't want to have to specify `Options` over and over to pass in all the options you need, you can use C# 6's using static feature to put them all in scope directly, giving you what you've got in your examples.

**Comment by danielmarbach** [comment]
But then you have to make this class partial and it can only be extended by
core things. And external package could not hook into that options approach

On Tuesday, March 8, 2016, Brandon Ording <notifications@github.com> wrote:

> If you wanted to improve the explorability of the API, all of the factory
> methods could be located inside a single static Options class, which
> would let you do something like:
>
> Options.Defer.By(TimeSpan.FromMinutes(15))
>
> And if you don't want to have to specify Options over and over to pass in
> all the options you need, you can use C# 6's using static feature to put
> them all in scope directly, giving you what you've got in your examples.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/NServiceBus/pull/3559#issuecomment-193525852>
> .
>


-- 
*Don't miss the Async/Await Webinar Series*
*• Learn more <http://go.particular.net/l/27442/2016-02-15/681bjl> →*

**Comment by timbussmann** [comment]
I think @danielmarbach is right there @bording. It would work for core options but also end up in quite a lot of noise (or requiring to use "advanced" language features which most users probably don't know of). Personally I think the downside of less explorable options is justified but again, this is a RFC ;)

**Comment by andreasohlund** [comment]
>Personally I think the downside of less explorable options is justified

Agreed, they are part of the advanced API so users needs to know what they are doing

**Comment by bording** [comment]
@danielmarbach True, I wasn't thinking about it needing to be extensible by downstream stuff as well.

I suppose you could position it as a `CoreSendOptions` or something like that and don't worry about extensibility. Then the downstreams could just implement their own `ISendOption` options which would still work with the Send/Publish/Reply methods even if they didn't appear in `CoreSendOptions`.

But I suppose that's not worth it.

**Comment by johnsimons** [comment]
This reminds me of the testing frameworks when they introduced the fluenty asserts:
```c#
Assert.That( array, Has.Exactly(1).EqualTo(3) );
Assert.That( array, Has.Exactly(2).GreaterThan(1) );
Assert.That(2+2, Is.EqualTo(4));
```
Sorry, I am not a great fan of all this ceremony.

I actually raised an issue about this, see https://github.com/Particular/NServiceBus/issues/3572 and to be honest I think this will make it worse.

IMHO, I would add public props to the `SendOptions` in the core, and external packages would use extension methods for get/set.

**Comment by andreasohlund** [comment]
>MHO, I would add public props to the SendOptions in the core, and external packages would use extension methods for get/set.

:-1: for different approaches if you are outside/inside the core, I'm :+1 for #3572

**Comment by danielmarbach** [comment]
@andreasohlund We pretty much ruled out fluent interfaces from the beginning. We agree that the implementation complexity is not worth the end-user benefit. We also agreed that fluent interfaces are becoming less and less popular these days.

**Comment by danielmarbach** [comment]
I still think discoverability is less compared to the extension method approach. Extension methods automatically get scoped to the type they extend and shown in intellisense. With this approach we wouldn't have that. We could get it by slightly tweaking the API a bit to do something like

```
session.Send(new object(), o =>
  o.DeferBy(TimeSpan.FromMinutes(15))
  o.Route.ToThisEndpoint()
  ...
  );
```

But then again we are in the land of fluent syntax nightmare. So I'm really on the fence...

**Comment by andreasohlund** [comment]
@timbussmann would you say this is important enough to consider for v6 based on the pain of testing or can we leave this for the next major?

**Comment by timbussmann** [comment]
we currently provide no further details on failed exceptions when using the testing framework because we can't get useful information out of `SendOptions`. That's the major downside of `SendOption`. It's something we can discuss for later versions as far as I can tell right now.

**Comment by andreasohlund** [comment]
Should we extract our findings into an issue flag the issue for vNext and close this pull?

**Comment by timbussmann** [comment]
@andreasohlund I'll raise an issue, ping the v6-task-force and close this one.

**Comment by timbussmann** [comment]
raised an issue here: https://github.com/Particular/NServiceBus/issues/3613

**Pull request closed without merging**
