### PR TITLE
Dynamic routing

### PR DESCRIPTION
**Pull request by johnsimons**
This PR adds support to NServiceBus to support dynamic routing at send time.

## What is dynamic routing
Dynamic routing is about **scaling out** at the client side.
The idea behind it is to instead of having the concept of a "Distributor" that does the "round robin" between all available workers, we are in essence doing the "distribution" at sending time.
This removes the need of the single "Distributor" because all clients can become "distributors".

## How do I use it
By default NServiceBus ships with a implementation of dynamic routing using the file system.
To start using it, you need to do the following:

1. Enable dynamic routing on your "senders"  

        BusConfiguration config = new BusConfiguration();
        config.UseDynamicRouting<FileBasedDynamicRouting>()
         .LookForFilesIn(pathtoLookForFiles);

1. Create routing files in `pathtoLookForFiles`, these files are plain txt files that contain a list of "workers", eg:

        Sales@MachineA
        Sales@MachineB
        Sales@MachineC
the file names need to match the convention, so if in your mapping declaration you have something like:

        <UnicastBusConfig ForwardReceivedMessagesTo="audit">
            <MessageEndpointMappings>
              <add Assembly="MyMessages" Type="MyMessages.Events.NewOrder" Endpoint="Sales@MachineA"/>
              <add Assembly="MyMessages" Type="MyMessages.Events.OrderMoreStock" Endpoint="Factory@MachineD"/>
            </MessageEndpointMappings>
        </UnicastBusConfig>
You would create 2 files named `Sales.txt` for `MyMessages.Events.NewOrder` and `Factory.txt` for `MyMessages.Events.OrderMoreStock`.
These files will be automatically monitored for changes.

## How to write a dynamic routing implementation
Let's say you want to write your own provider for dynamic routing.

1. You need to implement `IProvideDynamicRouting`, this is a very simple interface that either returns `true` when it has an address to provide for routing or `false` if there is no address.
When there is no address, the address defined in `<MessageEndpointMappings>` is used.
1. Create a class that derives from `DynamicRoutingDefinition`, this will give you the `config.UseDynamicRouting<MyDynamicRouting>()`
1. Create a feature that depends on `DynamicRouting` and registers your own implementation of `IProvideDynamicRouting`, eg:
    ```c#
    class MyCustomDynamicRouting : Feature
    {
        public MyCustomDynamicRouting()
        {
            DependsOn("DynamicRouting");
        }
    
        protected internal override void Setup(FeatureConfigurationContext context)
        {
    		context.Container.RegisterSingleton<IProvideDynamicRouting>(new MyCustomDynamicRoutingImpl());
        }
    }
    ```
        
1. That is it :smile:

## Safe to disconnect notifications
This provides the hooks for a 3rd party to be notified when is safe for an endpoint to be shutdown.
 
There are two parts to this solution:

1. Send message to endpoint, to trigger notification
This is done by sending a control message with a header named `NServiceBus.DisconnectMessage`.
You can also include extra headers, and these are passed to the observable event.
Here is an example:
    ```c#
    var transportMessage = ControlMessage.Create();
    transportMessage.Headers["NServiceBus.DisconnectMessage"] = "anything";
    transportMessage.Headers["MySpecialHeader"] = "foo";
    
    MessageSender.Send(transportMessage, new SendOptions("DynamicRouting.Receiver1"));
    ```

1. Subscribe to `BusNotifications.Endpoint.SafeToDisconnect` on the endpoint that is to be disconnected.
Here is an example:
    ```c#
    public class SubscribeToSafeToDisconnect : IWantToRunWhenBusStartsAndStops
    {
        readonly BusNotifications notifications;
    
        public SubscribeToSafeToDisconnect(BusNotifications notifications)
        {
            this.notifications = notifications;
        }
    
        public void Start()
        {
            notifications.Endpoint.SafeToDisconnect
                .ObserveOn(Scheduler.Default)
                .Subscribe(data =>
                {
                    var myHeaderValue = data.Headers["MySpecialHeader"];
                    // Do whatever here
                });
        }
    
        public void Stop()
        {
        }
    }
    ```

## How to override the default Translator on a transport implementation
```c#
public class MyTransport : ConfigureTransport
{
    protected override AddressTranslator Translator
    {
        get { return new MyTranslator(SafeRoleEnvironment.CurrentRoleInstanceId); }
    }

    class MyTranslator : AddressTranslator
    {
        readonly string instanceId;

        public MyTranslator(string instanceId)
        {
            this.instanceId = instanceId;
        }

        public override string Translate(Address address)
        {
            return address.Queue + instanceId; // Whatever the rules are
        }
    }
}
```

### CODE REVIEW

**Comment by pablocastilla** [comment]
Will it be possible to get the message and route by its properties? I think this is very interesing. For instance route by (source, priority and message type).

**Comment by andreasohlund** [comment]
At this stage no

https://github.com/Particular/NServiceBus/pull/2565/files#diff-6790849ea6400ab77bf006b37c15338bR8

That would add support for content based routing which so far we've choosen
to not support so far.

http://www.udidahan.com/2011/03/20/careful-with-content-based-routing/

**Comment by pablocastilla** [comment]
I see your point. But I see one limitation with the NSB routing, you can route by type and origin (the service that is running that .config and the type). But imagine I "really" need to route by one or two more concepts, for instance: priority and destiny, and each (origin,type,priority,destiny) could go to several endpoints for scaling out. At the end I would need to put something on top of the .Send, UtilProject.EspecialSend(message) that would be cleaner in the Dynamic Routing as a feature.

Just my opinion.

**Comment by andreasohlund** [comment]
@pablocastilla we do have future plans to provide dynamic routing based on the message type. As we build that I wouldn't be against making the "logical message" available to the "router" and by that making this type of routing possible.

ie:

`string IProvideDynamicRouting.FindRoute(LogicalMessage message)`

where [logical message](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Unicast/Messages/LogicalMessage.cs#L10) already today has "instance" and "headers"

Does this make sense?

**Comment by pablocastilla** [comment]
@andreasohlund It makes a lot of sense.

Thanks!

**Comment by johnsimons** [comment]
@andreasohlund I assume we are delaying this one and therefore it won't make it in v5.2 ?

**Comment by andreasohlund** [comment]
Correct!

**Comment by danielmarbach** [comment]
Can we close this?

**Comment by SzymonPobiega** [comment]
Replaced by https://github.com/Particular/PlatformDevelopment/issues/133 and associated PRs

**Comment by pablocastilla** [comment]
I have done this, I don't know if it is interesting for you, but we are able to scale out msmq without distributor and works really well.

https://pablocastilla.wordpress.com/2015/03/06/nservicebus-command-and-event-routing-in-database-with-scale-out/

**Comment by SzymonPobiega** [comment]
@pablocastilla that's exactly what we want to achieve but we want to make some of the routing concepts first class citizens so that there is no need for the downcasts you had to do. The current WIP PR for that is #2921. Please take a look and feel free to chime in.

**Pull request closed without merging**
