### PR TITLE
add failing test for dodgy nullable attribute

### PR DESCRIPTION
**Pull request by SimonCropp**
* `parameterinfo.name` can be null: https://docs.microsoft.com/en-us/dotnet/api/system.reflection.parameterinfo.name?view=netframework-4.8#remarks
 * used here with no null check https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/MessageInterfaces/MessageMapper/Reflection/ConcreteProxyCreator.cs#L128

Currently unable to find a workaround, so this is stopping development from moving forward since it blows up on startup.

For a smoke test in an endpoint. reference the dll in this assembly and try to start....

```
System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null. (Parameter 'name')
  Source=System.Private.CoreLib
  StackTrace:
   at System.Type.GetProperty(String name, BindingFlags bindingAttr)
   at NServiceBus.ConcreteProxyCreator.BuildCustomAttribute(Object customAttribute)
   at NServiceBus.ConcreteProxyCreator.AddCustomAttributeToProperty(Object customAttribute, PropertyBuilder propBuilder)
   at NServiceBus.ConcreteProxyCreator.CreateTypeFrom(Type type)
   at NServiceBus.MessageInterfaces.MessageMapper.Reflection.MessageMapper.GenerateImplementationFor(Type interfaceType)
   at NServiceBus.MessageInterfaces.MessageMapper.Reflection.MessageMapper.InnerInitialize(Type t)
   at NServiceBus.MessageInterfaces.MessageMapper.Reflection.MessageMapper.InitType(Type t)
   at NServiceBus.MessageInterfaces.MessageMapper.Reflection.MessageMapper.Initialize(IEnumerable`1 types)
   at NServiceBus.SerializationFeature.Setup(FeatureConfigurationContext context)
   at NServiceBus.Features.Feature.SetupFeature(FeatureConfigurationContext config)
   at NServiceBus.Features.FeatureActivator.FeatureInfo.InitializeFrom(FeatureConfigurationContext featureConfigurationContext)
   at NServiceBus.Features.FeatureActivator.ActivateFeature(FeatureInfo featureInfo, List`1 featuresToActivate, FeatureConfigurationContext featureConfigurationContext)
   at NServiceBus.Features.FeatureActivator.SetupFeatures(FeatureConfigurationContext featureConfigurationContext)
   at NServiceBus.FeatureComponent.Initalize(ContainerComponent containerComponent, FeatureConfigurationContext featureConfigurationContext)
   at NServiceBus.EndpointCreator.Initialize()
   at NServiceBus.EndpointCreator.CreateWithInternallyManagedContainer(EndpointConfiguration endpointConfiguration)
   at NServiceBus.Endpoint.Create(EndpointConfiguration configuration)
   at NServiceBus.Endpoint.<Start>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Program.<Main>d__0.MoveNext() in C:\Downloads\dodgyNullableSmokeTest\Endpoint\Program.cs:line 18

  This exception was originally thrown at this call stack:
	System.Type.GetProperty(string, System.Reflection.BindingFlags)
	NServiceBus.ConcreteProxyCreator.BuildCustomAttribute(object)
	NServiceBus.ConcreteProxyCreator.AddCustomAttributeToProperty(object, System.Reflection.Emit.PropertyBuilder)
	NServiceBus.ConcreteProxyCreator.CreateTypeFrom(System.Type)
	NServiceBus.MessageInterfaces.MessageMapper.Reflection.MessageMapper.GenerateImplementationFor(System.Type)
	NServiceBus.MessageInterfaces.MessageMapper.Reflection.MessageMapper.InnerInitialize(System.Type)
	NServiceBus.MessageInterfaces.MessageMapper.Reflection.MessageMapper.InitType(System.Type)
	NServiceBus.MessageInterfaces.MessageMapper.Reflection.MessageMapper.Initialize(System.Collections.Generic.IEnumerable<System.Type>)
	NServiceBus.SerializationFeature.Setup(NServiceBus.Features.FeatureConfigurationContext)
	NServiceBus.Features.Feature.SetupFeature(NServiceBus.Features.FeatureConfigurationContext)
    ...
```

The types need nullable enable to build this scenario. since u dont do VS2019 i couldnt add those types to the project. Hence i had to do a dll for the failing test

Offending types:
```
namespace WithDodgyNullable
{
    public interface IMyMessage 
    {
        string Schema { get; set; }
        string? Notes { get; set; }
    }

    public class MyMessage :
        IMyMessage,
        ICommand
    {
        public string Schema { get; set; } = null!;
        public string? Notes { get; set; }
    }
}
```

Note that if you enabled nullables on the core project this bug would be a build error not a runtime error

```
CS8604	Possible null reference argument for parameter 'name' in 'PropertyInfo? Type.GetProperty(string name, BindingFlags bindingAttr)'.
NServiceBus.Core (net452)
C:\Code\NServiceBus\src\NServiceBus.Core\MessageInterfaces\MessageMapper\Reflection\ConcreteProxyCreator.cs	128
```

### CODE REVIEW

**Comment by andreasohlund** [comment]
So in essense this prevents netcore 3.0 users to use interface messages with nullable properties if they have https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/nullable-reference-types turned on right?

**Comment by SimonCropp** [comment]
@andreasohlund yes. although it depends on their use of nullales. only certain nullabl scenarios trigger this

**Comment by andreasohlund** [comment]
>only certain nullable scenarios trigger this

Which one is the problematic one in your example?

**Comment by SimonCropp** [comment]
it was the combination. removing either did not result in an error. i think there is optimization as to what the default nullability is and how that is reflected in the attributes added to members

**Comment by andreasohlund** [comment]
Replaced by https://github.com/Particular/NServiceBus/pull/5481

**Pull request closed without merging**
