### PR TITLE
Update PR merge policy

### PR DESCRIPTION
**Pull request by dbelcham**
Update the Review Guidelines to reflect our policy on merging PRs

### CODE REVIEW

**Comment by bording** [comment]
@dbelcham I'm not sure this is correct. I'm don't think there's a case for using Rebase and Merge. If you want to retain the commits, I think a regular merge commit makes more sense.

When the Squash and Merge happens, GH includes the PR number in the commit message (by default, anyway) and I like seeing that so I know what PR is responsible for the changes. I don't think you'd retain any of that with the Rebase and Merge option.

**Comment by dbelcham** [comment]
@bording tests show that you are correct. A Rebase & Merge doesn't include the PR#. So are you suggesting that our two options are Squash & Merge or just Merge? Or only Squashing. I'm guessing the former.

**Comment by bording** [comment]
Squash and Merge (and retain the PR# in the commit message) if we don't want the intermediate commits, and a regular merge with merge commit if we do.

**Comment by dbelcham** [comment]
Stumbled on the Settings area in a different github repo last night and noticed that you can actually turn on/off the different Merge button options at a repo level now. Should we do that to remove the Rebase option at the same time as we push this to `develop`?

**Comment by timbussmann** [comment]
so far I was using the `rebase and merge` option for single-commit PRs but I like @bording point. If we agree to not do that, we should indeed deactivate that button 👍

**Comment by dbelcham** [comment]
`Rebase and merge` option has been disabled for this repo

**Pull request merged**
