### PR TITLE
AT for broadcast + slight API rename

### PR DESCRIPTION
**Pull request by SzymonPobiega**
* Renamed `SetDistributionStrategy` to `Set` as per @SeanFeldman 's suggestion
 * Added an acceptance test to verify that overriding distribution strategies works (and that `AllInstancesDistributionStrategy` does what it is supposed to do)

### CODE REVIEW

**Comment by SzymonPobiega** [comment]
@janovesk @SeanFeldman @Particular/nservicebus please review

**Comment by janovesk** [comment]
No so sure I agree on this one. 

What are you setting when you `Set()` on a `DistributionPolicy`? With no more information available I would assume I was setting the entire `DistributionPolicy` through a static helper method. 

But you are not.. you are actually setting the `DistributionStrategy` for a specific subset of types. All the tuples of `<DistributionStrategy,types> make up the `DistributionPolicy` for the endpoint.

**Comment by janovesk** [comment]
Do we need to expose `DistributionPolicy` at all? The only thing it will be used for is setting the routing strategies. How about changing the public api to something like this?

```c.Routing().SetDistributionStrategy(new AllInstancesDistributionStrategy(), t => t == typeof(Request))```

**Comment by SzymonPobiega** [comment]
:+1: for `c.Routing().SetDistributionStrategy`. Let me do the change

**Comment by SzymonPobiega** [comment]
@janovesk updated

**Comment by janovesk** [comment]
Looks good.

**Comment by SeanFeldman** [comment]
@janovesk I did not realize that you can _add_ multiple policies. If that's the case, then it's not Setting, but adding I'd think.

**Comment by janovesk** [comment]
You can't add multiple policies. You set a strategy per message type/set of message types. These strategies together form the policy.

**Comment by SeanFeldman** [comment]
I failed to understand it from the API :(

**Pull request merged**
