### PR TITLE
Fixed MessageEndpointMapping interpretation to honor the proper ordering

### PR DESCRIPTION
**Pull request by SzymonPobiega**
Connects to Particular/V6Launch#68

### CODE REVIEW

**Comment by SzymonPobiega** [comment]
@timbussmann @DavidBoike @bording please review. I'll do the same change in #4041 so that if #4041 is merged we can forget about this one.

**Comment by timbussmann** [comment]
I like the added unit tests :+1:

**Comment by DavidBoike** [comment]
:+1:

**Comment by bording** [comment]
LGTM. #4041 already has plenty going on, so I'm going to go ahead and merge this.

**Pull request merged**
