### PR TITLE
clean up obsoletes

### PR DESCRIPTION
**Pull request by SimonCropp**
do we need all the methods with no obsolete info?

### CODE REVIEW

**Comment by SimonCropp** [comment]
@Particular/nservicebus thoughts

**Comment by SzymonPobiega** [comment]
So the general guidance is to remove all members if a type of being obsoleted?

**Comment by SimonCropp** [comment]
@SzymonPobiega i think unless you want to provide specific obsoletes for the various members.  Can u see any problems with this approach?

**Comment by andreasohlund** [comment]
I like it

**Comment by SzymonPobiega** [comment]
@SimonCropp I like the approach. I was asking to understand better because I have close to zero experience with this aspect of releasing stuff.

**Comment by SzymonPobiega** [comment]
@SimonCropp @andreasohlund I assume I can now merge?

**Pull request merged**
