### PR TITLE
Add context to CustomConfig call

### PR DESCRIPTION
**Pull request by Tra5is**
Issue #3202

### CODE REVIEW

**Comment by danielmarbach** [comment]
@Tra5is this needs a rebase.

I'm :+1: to pull this in. Makes the API consistent with the `when` where you optionally get context access.

**Comment by danielmarbach** [comment]
I just realized that we essentially already have it built in but in a no strongly typed fashion. See

https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.AcceptanceTesting/Support/EndpointRunner.cs#L43

this runs before CustomConfig.

Therefore you can do the following:

        e.CustomConfig(c =>
        {
            var context = c.GetSettings().Get<YourScenarioContext>();
            // do fancy things with the context.
        }));

cc @timbussmann

**Comment by timbussmann** [comment]
Changes look good :+1: Makes the API more consistent. But please note develop is already targeting v6, so we may need to backport this to v5?

@Tra5is can you please sign the [CLA](http://www.particular.net/contributors-license-agreement-consent) so we can merge this after a rebase?

**Comment by Tra5is** [comment]
For the time being we're still targetting V5 so we'll need it backported. 

I've signed the CLA.

Do I need to rebase this commit?

**Comment by timbussmann** [comment]
> I've signed the CLA.

great, thanks!

> Do I need to rebase this commit?

Yes you need to rebase since we can't merge it with conflicts. Let us know if you're having troubles with rebasing.

**Pull request closed without merging**
