### PR TITLE
Expose audit expiration setting

### PR DESCRIPTION
**Pull request by andreasohlund**
Since the external msmq transport needs it

### CODE REVIEW

**Comment by dbelcham** [comment]
@andreasohlund I tweaked a couple of the public comments, otherwise it looks good

**Comment by andreasohlund** [comment]
Awesome

**Comment by bording** [comment]
I also added the relevant stuff from #4767.

**Comment by bording** [comment]
Since @dbelcham had approved earlier, I'm going to go ahead and merge this.

**Pull request merged**
