### PR TITLE
add internal class namespace convention

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by timbussmann** [comment]
@SimonCropp is that convention documented anywhere?

**Comment by SimonCropp** [comment]
No it is not. Tbh i could not think of a way to document it that would add value over just having a test that verifies it. Happy to hear suggestions @timbussmann

**Comment by timbussmann** [comment]
the test certainly helps but I think it would be useful to have a short description and reason of existing conventions in the pdev/guidelines folder. Same applies for not using readonly, discussions about interface namings, guidelines on when/how to write (which) tests. and so on.

**Comment by andreasohlund** [comment]
Since this is NSB specific should we have it in the NSB wiki? (since it is interesting for contributors as well)

**Comment by timbussmann** [comment]
not a huge fan of the wikis, but for that case it would make sense. :+1:

**Comment by andreasohlund** [comment]
Another option is a `gh-pages` branch

**Comment by andreasohlund** [comment]
So how about we add a restricted set of allowed namespaces to the test:

`NServiceBus`
`NServiceBus.Transport`
`NServiceBus.Persistence`
`NServiceBus.Pipeline`
`NServiceBus.Serialization`
`NServiceBus.Container`

Then we can add new ones as we see the need for it?

**Pull request merged**
