### PR TITLE
Send local async

### PR DESCRIPTION
**Pull request by danielmarbach**
This PR is part of the work to make the core async enabled. For more background read [Async/Await: It's time!](http://particular.net/blog/async-await-its-time) blogpost

Dependency https://github.com/Particular/NServiceBus/pull/2890

`SendLocal` is now async

Merge this *AFTER* the dependency

### CODE REVIEW

**Comment by danielmarbach** [comment]
Rebased

**Comment by danielmarbach** [comment]
Rebased. Again

**Comment by danielmarbach** [comment]
Anyone had time to review this?

**Comment by andreasohlund** [comment]
Looks all good, can't seem to merge though? (1 more rebase? :( )

**Comment by danielmarbach** [comment]
@andreasohlund rebased

**Pull request merged**
