### PR TITLE
Remove AllInstancesDistributionStrategy

### PR DESCRIPTION
**Pull request by DavidBoike**
We should not have this as a public type without a use. "Broadcasting a command" blurs the line between commands and events and has the potential to allow our customers to shoot themselves in the foot.

/cc @mauroservienti

### CODE REVIEW

**Comment by bording** [comment]
LGTM

**Comment by mauroservienti** [comment]
LGTM sa well

**Comment by danielmarbach** [comment]
Before we merge this I would like to get some input from @SzymonPobiega

**Comment by timbussmann** [comment]
:+1: (but do we have an acceptance test which tests the usage of a custom distribution strategy?)

**Comment by SzymonPobiega** [comment]
How about moving this one to a sample instead of killing it? BTW, I don't mind removing it from the core.

**Comment by timbussmann** [comment]
> How about moving this one to a sample instead of killing it? BTW, I don't mind removing it from the core.

A sample sounds good to me (since we could use a simple sample around distributionstrategy anyway).

**Comment by danielmarbach** [comment]
@SzymonPobiega can you raise a docs issue? 

I'll merge this then

**Comment by SzymonPobiega** [comment]
@danielmarbach Issue raised https://github.com/Particular/docs.particular.net/issues/1733

**Pull request merged**
