### PR TITLE
Check endpoint name for invalid @ characters

### PR DESCRIPTION
**Pull request by timbussmann**
fixes https://github.com/Particular/NServiceBus/issues/3906

Should we provide better exception messages here?

@Particular/nservicebus-maintainers please review

### CODE REVIEW

**Comment by bording** [comment]
> Should we provide better exception messages here?

Did you have something in mind? What you have here seems fine to me.

:+1:

**Comment by danielmarbach** [comment]
Agree with @bording this is good enough

**Comment by timbussmann** [comment]
what version are you working with @kristianjaeger ? The `MessageEndpointMappings` section should still allow `@` in NServiceBus v6, `MessageEndpointMappings`  has been removed from v7 though and the recommended approach is to use the instance mapping file when running with MSMQ. But you can also specify the machine with a code first API, see https://docs.particular.net/transports/msmq/routing?version=msmqtransport_1#custom-instance-mapping

**Comment by kristianjaeger** [comment]
Thanks, @timbussmann . I'm using 6.3.4 on a project.  I can take another look.  I found that the custom instance mapping API worked well for my situation.  Cheers.

**Pull request merged**
