### PR TITLE
Document required steps to run ATT locally

### PR DESCRIPTION
**Pull request by timbussmann**
After going through the pain today, I think it would make sense to document the required steps and settings in the repositories?

Something else to add?

@Particular/azure-maintainers  what do you think?

### CODE REVIEW

**Comment by bording** [comment]
Should this PR have been opened on https://github.com/Particular/NServiceBus.AzureStorageQueues instead?

**Comment by danielmarbach** [comment]
Yeah seems alien here

**Comment by SeanFeldman** [comment]
I like what @timbussmann did. If changed to general `Transport.UseSpecific` and `Persitence.UseSpecific`, explaining the naming convention, it becomes applicable to any transport/persistence and not just Azure related ones.

**Comment by danielmarbach** [comment]
Even if it is "generyfied". I'm still hesitant whether it belongs to the readme in this repo. I would rather use a wiki or a markdown in platform dev.

**Comment by timbussmann** [comment]
sorry guys, no idea how I managed to change this on the core. Of course this should be against the ASQ repo. Will close and create a new one.

**Comment by timbussmann** [comment]
@SeanFeldman raised again here: https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/85

**Pull request closed without merging**
