### PR TITLE
Properly setting ProcessedAt

### PR DESCRIPTION
**Pull request by danielmarbach**
Connects to #3450

@WojcikMike @johnsimons thoughts?

@Particular/nservicebus-maintainers please review

### CODE REVIEW

**Comment by WojcikMike** [comment]
I like it, Looked at the code and have only one suggestion. Would it make sense to move the test:
Performance/When_message_is_audited.cs
To some other namespace/directory than Performance. As it seems completely not related to performance. The rest looks good to me

**Comment by danielmarbach** [comment]
@WojcikMike I think we have a few other tests that are misplaced in that directory. We might even need to rename the folder to something like statistics. I think we should treat it outside this PR

**Comment by WojcikMike** [comment]
@danielmarbach :+1: I am fine with doing it in another PR.

**Comment by johnsimons** [comment]
I am not sure this is working correctly.

From my testing it seems things are executing in the following order:

1. state.ProcessingStarted = DateTime.UtcNow;
1. UoW.Begin
1. Mutate incoming
1. Invoke handler
1. Mutate outcoming
1. state.ProcessingEnded = DateTime.UtcNow;
1. Audit message sent
1. UoW.End

As u can see it seems UoW.End is executed outside the processing statistics
Also, I would have expected Audit message sent to be executed after UoW.End

So IMO the execution order should be:

1. state.ProcessingStarted = DateTime.UtcNow;
1. UoW.Begin
1. Mutate incoming
1. Invoke handler
1. Mutate outcoming
1. UoW.End
1. state.ProcessingEnded = DateTime.UtcNow;
1. Audit message sent

**Comment by danielmarbach** [comment]
I quickly spiked the following

* Splitting UnitOfWorkBehavior into two parts
* Moving ProcessingStatiticsBehavior into ReceiveFeature.

here is the outcome


```
------------------------ ProcessingStatisticsBehavior
------------------------ BeginUnitOfWorkBehavior
------------------------ Begin UnitOfWork
------------------------ MutateIncomingTransportMessageBehavior
------------------------ MutateIncomingMessageBehavior
------------------------ EndUnitOfWorkBehavior
------------------------ InvokeHandlerTerminator
------------------------ End UnitOfWork
------------------------ InvokeAuditPipelineBehavior
------------------------ AuditProcessingStatisticsBehavior
```

**Comment by andreasohlund** [comment]
@WojcikMike here is the discussion around why the folder was called `Performance` https://github.com/Particular/Vision/issues/5

can you chime in there?

**Comment by danielmarbach** [comment]
@andreasohlund my proposal will move it into the Pipeline/Incoming folder

**Comment by andreasohlund** [comment]
I think that's fine, what we want is there to be "pipeline notifications" for the above and then we can have a "performance" notification thing on top that emits the critical time/processing time/ etc data on top of that.

Ie: You are dealing with the infrastructure, and the performance "capability" will work on top of that?

**Comment by johnsimons** [comment]
@danielmarbach I am not sure processing time should include the auditing of a message, to me that is a different stat

**Comment by andreasohlund** [comment]
@johnsimons good question, I'm pretty sure that we've always defined "critical time" as time it took for the message to be send and later successfully processed. My personal opinion is that "successfully processed" should be as close as possible to "receive transaction committed", and this would include the sending of the audit message since a user investigating performance issues would like to have as accurate metrics as possible. @udidahan can you confirm?

This highlights a major flaw in the current way we piggy back performance info with the audit message since we have to take the time where the audit messages is sent. If the audit gets slow the header won't capture that but the performance counter will. 

So in essense `CriticalTime perf counter` != `Critical time calculated on audit messages`

Note: v5 has the same behavior so this is not a new issue introduced in v6

**Comment by danielmarbach** [comment]
Based on the discussion point raised by @andreasohlund I pushed a fix which doesn't affect the counters but fixes the processed at headers.

**Comment by andreasohlund** [comment]
Looks good to me

**Comment by udidahan** [comment]
> My personal opinion is that "successfully processed" should be as close as possible to "receive transaction committed", and this would include the sending of the audit message since a user investigating performance issues would like to have as accurate metrics as possible. @udidahan can you confirm?

Confirmed.

**Comment by andreasohlund** [comment]
@johnsimons @udidahan raised a different issue to track the "" between the value we set on the audit message, the value we use for the perf counter and the "real" value

https://github.com/Particular/NServiceBus/issues/3494

**Pull request merged**
