### PR TITLE
[SPIKE] Avoid array allocation in writing log

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by timbussmann** [comment]
Did you notice an improvement in memory allocation with this change?

**Comment by Scooletz** [comment]
@SimonCropp Have you considered a `Serilog` like non-allocating non-boxing approach providing generic methods instead of ones accepting `object`. An example: https://github.com/serilog/serilog/blob/dev/src/Serilog/Core/Logger.cs#L212 ?

**Comment by SimonCropp** [comment]
@Scooletz yeah. but i figured i would get this one through first :)

**Comment by SimonCropp** [comment]
@timbussmann https://github.com/Particular/PlatformDevelopment/issues/1390#issuecomment-318268688

**Comment by andreasohlund** [comment]
@Particular/nservicebus-maintainers we need to make a call if we should include this in v7 or not?

**Comment by bording** [comment]
The @Particular/nservicebus-maintainers discussed this today, and while it's too late to take this for v7, we do want to include this in v8.

**Comment by SimonCropp** [comment]
Give this only effects the downstream logging libs, and i am more than happy to handle that breaking change, there is no reason this cannot be pulled in as part of v7

**Comment by bording** [comment]
@SimonCropp We discussed this again, and we decided that since we are still taking other v7 changes, we'll go ahead and take this too. I had to open a new PR: #5037.

**Pull request closed without merging**
