### PR TITLE
Cleaned up routing APIs

### PR DESCRIPTION
**Pull request by SzymonPobiega**
* `EndpointName` -> `Endpoint`
 * `EndpointInstanceName` -> `EndpointInstance`
 * `UnicastRoutingTable.AddStatic` -> `RouteToEndpoint(string)` / `RouteToAddress(string)`
 * Removed `UnicastRoutingTable.AddStatic(EndpointInstance)`

### CODE REVIEW

**Comment by SzymonPobiega** [comment]
@johnsimons @SimonCropp @janovesk  what we discussed on last call. @SeanFeldman I've renamed the `EndpointName` as you suggested.

**Comment by johnsimons** [comment]
@SzymonPobiega can you please show us what the api now looks like from a developer perspective vs a {DEV}OPS ?
Maybe also  a simple scenario like I want to send all messages in AssemblyA to EndpointX ?

**Comment by johnsimons** [comment]
Also, [DEV]OPS wants to override the pyhsical routing via some infrastructure code, how do they go about doing this ?

**Comment by SzymonPobiega** [comment]
Rebased. Can this be reviewed without waiting for the doco updated? It is sort of orthogonal.

**Comment by johnsimons** [comment]
@SzymonPobiega I am not asking you to write the doco in the docs website, all I am asking is for you to document the proposed api in the description of this PR, I find that much more informative and easier to discuss, and also it kind of usable later for when you write the real doco.

**Comment by SzymonPobiega** [comment]
@johnsimons I thought the description is clear. This PR is a bunch of renames we agreed on during a call we have with @SimonCropp. Not sure what else I can add here.

**Pull request merged**
