### PR TITLE
[WIP] test for Dev-Saga-Persister

### PR DESCRIPTION
**Pull request by timbussmann**
@andreasohlund here's a failing test to describe what I meant.

(to be fair, it also seems to fail using inmem persistence)

### CODE REVIEW

**Comment by andreasohlund** [comment]
Reusing saga timeouts is not something I ever seen in the wild. Should we consider preventing it?

**Comment by andreasohlund** [comment]
I think this might be a core bug, lets talk it through on the maintainer sync today

**Comment by dbelcham** [comment]
Was there any outcome from the sync call?

**Comment by andreasohlund** [comment]
We hit a deep 🐰 🕳 . Follow up call with @SimonCropp and @timbussmann will happen tomorrow

**Comment by andreasohlund** [comment]
Had a call with @timbussmann and @SimonCropp and we concluded:

1. To tighten up the core to require the `NServiceBus.SagatType` header to match an existing saga type if present (for now it would be up to persisters to provide support for migration, eg Attribute + injected behavior that changes the header)
2. In the long run consider if this can be releaxed, esp when we change the saga it to a string persisters could easily prefix the string with a "sagatype-id" and then string split if needed to avoid embedding that info in stored ids. 

I will do a spike for the no1 action point

**Comment by andreasohlund** [comment]
Replaced by https://github.com/Particular/NServiceBus/pull/4514

**Pull request closed without merging**
