### PR TITLE
update Fody to get clean build

### PR DESCRIPTION
**Pull request by zbrad**
had to update Fody to get clean build in master branch

### CODE REVIEW

**Comment by SimonCropp** [comment]
@Particular/nservicebus-maintainers what do we do with this one. it is a valid complaint. i think the only way to fix it without a release is to do a direct commit on master

@zbrad thanks for this.

**Comment by ramonsmits** [comment]
@SimonCropp I suggested such a thing a time ago to do on a support branch and that was declined. Not saying that I'm against it but I used the argument that we don't know if the next version will be a patch or a minor and I thought it was valid to then put on the support branch.

**Comment by andreasohlund** [comment]
Having the master in a compiling state seems legit to me. We can just commit and move the tag?

That said can't we just bundle it with https://github.com/Particular/NServiceBus/issues/3468 ?

**Comment by danielmarbach** [comment]
@andreasohlund that was the plan

**Comment by ramonsmits** [comment]
@zbrad Closing this PR but your commit is included in #3518

**Comment by timbussmann** [comment]
reopening this issue since the PR fixing this issue was closed.

**Comment by andreasohlund** [comment]
How about we merge this into a `release-5.3.0` branch and park it there?

we could merge to master and move the tag as well? (and not release )

**Comment by danielmarbach** [comment]
Let's merge into master and move the tag. Having a non-compiling master is a PITA

**Comment by andreasohlund** [comment]
:+1:

**Comment by ramonsmits** [comment]
@danielmarbach @andreasohlund  We cannot, as that violates our own rules. That is why I made Particular/PlatformDevelopment#663

**Comment by danielmarbach** [comment]
Yes we can, rules are guidelines. When we have strong arguments to violate the rule we can do it.

**Comment by andreasohlund** [comment]
Agree with @danielmarbach the pragmatic way it to just move the tag. This is unlikely to happen again so lets not overthink this?

**Comment by ramonsmits** [comment]
So that means we can then merge #3511 as there are equally strong argument to merge that to support-4.7 too?

**Comment by andreasohlund** [comment]
>So that means we can then merge #3511 as there are equally strong argument to merge that to support-4.7 too?

:+1: just as long as we move the tags as well so a local merge is likely the best way to do it so you can push the tags at the same time?

**Comment by danielmarbach** [comment]
Done as of https://github.com/Particular/NServiceBus/commit/7e7c5f6b31399ffba847702c5e9397f3577283c4 moved the tag as well

Thanks again @zbrad !

**Comment by danielmarbach** [comment]
@zbrad would it be possible for you to quickly sign the CLA?

http://particular.net/contributors-license-agreement-consent

Thanks!

**Comment by ramonsmits** [comment]
@danielmarbach We should not move the version tag. Now there is a disconnect between what is build and deployed versus the code repo.

**Comment by danielmarbach** [comment]
@ramonsmits We need to. GitVersion would trip over otherwise

**Comment by zbrad** [comment]
I re-re-signed it, there should have been a previous signing on file.

**Comment by danielmarbach** [comment]
@zbrad thanks.

**Comment by malkinservicebus** [comment]
@zbrad Thanks for your contribution to NSB code. We have a surprise for you!
Please forward your email address to operations@nservicebus.com
Thanks again!
Malki

**Pull request closed without merging**
