### PR TITLE
Obsoleting unused distributor config properties from UnicastBusConfig

### PR DESCRIPTION
**Pull request by mat-mcloughlin**
Connects to https://github.com/Particular/NServiceBus/issues/3426

Doco pull: https://github.com/Particular/docs.particular.net/pull/1155

@timbussmann can you please check this is correct

### CODE REVIEW

**Comment by timbussmann** [comment]
@SzymonPobiega @janovesk is it ok to obsolete these properties without any replacement type or can we hint at some new configuration option?

**Comment by janovesk** [comment]
The replacement is the `EnlistWithLegacyMSMQDistributor` code first API mentioned by @SzymonPobiega [here](https://github.com/Particular/NServiceBus/issues/3426#issuecomment-181447612).

**Comment by mat-mcloughlin** [comment]
Sorry @timbussmann @janovesk missed that. I've added a message now

**Comment by timbussmann** [comment]
changes look good to me, @SzymonPobiega @janovesk can you review and check the messages for correctness?

@mat-mcloughlin do we need to update docs or samples?

**Comment by SzymonPobiega** [comment]
:+1:

**Comment by janovesk** [comment]
Just a small thing: to stay consistent with other obsolete messages, I'd add some parentheses to indicate that `EnlistWithLegacyMSMQDistributor()` is actually a method.

**Comment by timbussmann** [comment]
@janovesk we don't use paranthese on the `ForwardReceivedMessagesTo` message. I'm not sure if it could confuse readers because it's actually not a parameterless method?

**Comment by andreasohlund** [comment]
The removed settings are still mentioned in

http://docs.particular.net/nservicebus/scalability-and-ha/distributor/#worker-configuration-when-hosting-in-nservicebus-host-exe

and also in:

http://docs.particular.net/samples/scaleout/#Nuget-v6-pre

let's get a doco pull going as well? (or do you have plans to deal with this already @SzymonPobiega and @janovesk )

**Comment by andreasohlund** [comment]
synced with @mat-mcloughlin and the doco pull is already opened, so I'm :+1: to merge

**Pull request merged**
