### PR TITLE
NServiceBus.Pipeline namespace

### PR DESCRIPTION
**Pull request by timbussmann**
* moves all context interfaces to the `NServiceBus.Pipeline` namespace
* merges many other pipeline related namespaces into `NServiceBus.Pipeline`

Connects to Particular/PlatformDevelopment#187

### CODE REVIEW

**Comment by timbussmann** [comment]
@Particular/nservicebus @Particular/tf-handlercontext please review

**Comment by timbussmann** [comment]
rebased

**Comment by danielmarbach** [comment]
If I recall correctly v5 had incoming and outgoing context. Do we need a mention in the upgrade guide?

**Comment by andreasohlund** [comment]
Looks :+1: 

This will break doco, callback  and rabbitmq so we need to line up pulls for those

It might break NH and raven as well (not sure if they still use behaviors)

**Comment by timbussmann** [comment]
@Particular/nservicebus rebased again. Please merge. Will open doco PRs and check for downstream repos as soon as merged.

**Comment by indualagarsamy** [comment]
@timbussmann - Can you create the associated doco PRs and associate them to this PR? Thanks.

**Comment by danielmarbach** [comment]
@indualagarsamy would you prefer PR with unstable local build then before this get merged?

**Comment by indualagarsamy** [comment]
@danielmarbach @timbussmann - Just to be clear.
Please add an associated WIP doco PR so we can track documentation better, before merging this PR.

**Comment by SimonCropp** [comment]
@danielmarbach 

> would you prefer PR with unstable local build then before this get merged

that is acceptable for a WIP PR on docs. i would even be happy with a monkey patched dll in the current local packages dir.

The aim here is twofold

 1. Exercise the API as early in the process as possible to catch problems earlier
 2. Reduce the time taken between a merge on an upstream and the eventual downstream update.

The value of above two trump the fact that the build server will be temporarily red for that PR

I understand there are some manual hacks involved in making this work. but those hack are temporary, not time consuming and fairly straight forward.

**Comment by timbussmann** [comment]
@indualagarsamy @SimonCropp added doco PR

**Comment by andreasohlund** [comment]
@janovesk this will break the gateway right?

**Comment by andreasohlund** [comment]
Synced with @timbussmann and he's ready to fix the downstreams. 

Merging this since it's not likely to cause us to change anything in this pull based on downstream feedback

**Comment by janovesk** [comment]
Only trivial changes necessary for the [v6 PR of the gateway](https://github.com/Particular/NServiceBus.Gateway/pull/17/) because of this. @andreasohlund @timbussmann

**Comment by timbussmann** [comment]
@janovesk should be able to update as soon as https://github.com/Particular/NServiceBus.Callbacks/pull/9 is merged and pushed to the MyGet feed.

**Pull request merged**
