### PR TITLE
Avoid exceptions when FileName not set on FileLoadException

### PR DESCRIPTION
**Pull request by timbussmann**
backports fixes related to https://github.com/Particular/NServiceBus/issues/2722 to latest v5.

This hasn't been tested yet.

### CODE REVIEW

**Comment by andreasohlund** [comment]
LGTM

How do we test this?

**Comment by timbussmann** [comment]
@andreasohlund that's the tricky question. So far I'm not aware of a good way to reproduce it. Note that this code is basically the same as the v6 implementation.

**Comment by danielmarbach** [comment]
Is the lib update really needed? It seems the first commit compiled happily

**Comment by timbussmann** [comment]
@danielmarbach hm, pretty sure it didn't before the lib update. Will have a closer look.

**Pull request merged**
