### PR TITLE
public api has to indicate that stop method is async

### PR DESCRIPTION
**Pull request by SeanFeldman**
As per discussion with @danielmarbach

### CODE REVIEW

**Comment by andreasohlund** [comment]
Why didn't we make the `.Start` async as well?

**Comment by SeanFeldman** [comment]
Start kicks off transport`s internal notifiers. Notifiers will notify upon
message arrival, but caller of `.Start()` doesn't have to await.
With `Stop()` it's different, since we need to wait for messages in flight
to be done and transport notifiers to shut down.

**Comment by andreasohlund** [comment]
Got it!

**Comment by danielmarbach** [comment]
:+1:

**Pull request merged**
