### PR TITLE
Xml serializer refactoring part II

### PR DESCRIPTION
**Pull request by danielmarbach**
I quickly discussed this with @johnsimons, here is my attempt to make the deserializer more expressive by using descriptive method names.

### CODE REVIEW

**Comment by danielmarbach** [comment]
One thing that I noticed while doing the small refactoring is that https://github.com/Particular/NServiceBus/blob/XmlSerializer_Refactoring/src/NServiceBus.Core/Serializers/XML/Serializer.cs#L38 calls InitializeNamespace but never uses the namespace returned by the method. The method is called again here https://github.com/Particular/NServiceBus/blob/XmlSerializer_Refactoring/src/NServiceBus.Core/Serializers/XML/Serializer.cs#L334 and then the return value is used. But I see the first call is currently necessary because this here seems to assume that the nameSpacesToAdd is set correctly. Should I change this also?

**Comment by danielmarbach** [comment]
@johnsimons feel free to review

**Comment by johnsimons** [comment]
The changes so far seem to make the code more readable, so I'm :+1:

**Comment by johnsimons** [comment]
Regarding the `nameSpacesToAdd`, I think what you saying makes sense @danielmarbach, I would change that to make it more readable and maintainable.

**Comment by andreasohlund** [comment]
I like the changes, +1

**Comment by danielmarbach** [comment]
@johnsimons I refactored the namespacesToAdd usage. Please review

**Comment by johnsimons** [comment]
:+1:

**Comment by danielmarbach** [comment]
@andreasohlund did you bump to V6? Can I merge these changes?

**Comment by andreasohlund** [comment]
Not bumped, go ahead with nextversion.txt
https://github.com/ParticularLabs/GitVersion/wiki/Bumping-versions

**Comment by danielmarbach** [comment]
Thought you don’t like checking in files?

**Comment by andreasohlund** [comment]
I don't but there is not other option :( other than leaving develop as is
and start on `release-6.0`

**Pull request merged**
