### PR TITLE
SagaId passed into persister is no longer restricted to be a Guid

### PR DESCRIPTION
**Pull request by danielmarbach**
Discussed with @andreasohlund 

I assumed `IContainsSagaData` should still be the same for the moment.

### CODE REVIEW

**Comment by colin-higgins** [comment]
Would an overload for Guid make sense? Would break less user code.

**Comment by andreasohlund** [comment]
> Would an overload for Guid make sense? Would break less user code.

Are you talking about `ISagaPersister`? 
Assuming yes we're the only ones calling that method so I don't see how that would help the end users?

**Comment by colin-higgins** [comment]
Ah, please disregard then

**Comment by SimonCropp** [comment]
Canyou include some docoon how existing persistes (especially community ones) should transition over?

**Comment by danielmarbach** [comment]
@andreasohlund should we close this one and treat it as a TODO item in the saga revamp epic?

**Pull request closed without merging**
