### PR TITLE
Add TestCase to transport test

### PR DESCRIPTION
**Pull request by dbelcham**
Add TestCase to test that had hard coded transaction scope

### CODE REVIEW

**Comment by andreasohlund** [comment]
So the purpose here is just to document that the other modes are not relevant right?

If so wouldn't `[Test]//Only relevant for transaction scope mode` be more terse?

**Comment by dbelcham** [comment]
Both that and to make it so that transport level configuration of the test suite can override and exclude/include tests in their test runs appropriately.

**Comment by danielmarbach** [comment]
@andreasohlund as @dbelcham mentioned the skipping part is important.

**Comment by danielmarbach** [comment]
This will affect downstream transport tests. When is the right time to send in the downstream PRs?

**Comment by andreasohlund** [comment]
Wouldn't the downstreams that don't support this have already just deleted the file? (so we don't have to update them)

**Pull request merged**
