### PR TITLE
HandleCurrentMessageLater causes message loss when using Outbox

### PR DESCRIPTION
**Pull request by timbussmann**
fixes https://github.com/Particular/NServiceBus/issues/4993

### CODE REVIEW

**Comment by timbussmann** [comment]
are the build failures related to the approval-file location changes by @bording on v7? Any way to fix this?

**Comment by dbelcham** [comment]
@timbussmann I made a tweak to the builds and kicked off the build again. Will know in a few minutes

**Comment by dbelcham** [comment]
@timbussmann looks like it fixed most of the problems. You still have one failing test `ConventionEnforcementTests.Ensure_all_messages_are_public` which looks to be a legitimate problem. The Inspections test run can be marked a successful since it is a set of known issues.

**Comment by timbussmann** [comment]
fixed the `Ensure_all_messages_are_public` test. Should be good now.

**Pull request merged**
