### PR TITLE
Removed TransportMessage in favor of IncomingMessage and OutgoingMessage

### PR DESCRIPTION
**Pull request by danielmarbach**
@andreasohlund as discussed.

I think I destroyed an edge case with the message id. I can't finish it. Can you take this over?

Most likely those ATTs are going to fail

* `When_sending_with_no_correlation_id.Should_use_the_message_id_as_the_correlation_id`
* `When_sending_to_another_endpoint.Should_receive_the_message`

### CODE REVIEW

**Comment by danielmarbach** [comment]
@andreasohlund ping me when this is green. Going to write the doco then in my spare time.

**Comment by andreasohlund** [comment]
Rebased

**Comment by andreasohlund** [comment]
@danielmarbach let me know if you need help with the doco

**Comment by danielmarbach** [comment]
I pushed the doco PR

**Pull request merged**
