### PR TITLE
Show how to opt-out from style cop analysis

### PR DESCRIPTION
**Pull request by danielmarbach**
Would normally trigger

image

### CODE REVIEW

**Comment by danielmarbach** [comment]
@adamralph as discussed

**Comment by adamralph** [comment]
@danielmarbach nice!

**Comment by andreasohlund** [comment]
Cool, so in essence we should rename all source package files to .g,cs?

**Comment by adamralph** [comment]
That would get consuming packages unstuck, but should also consider how, when we enable a new rule in Particular.CodeRules, will we fix violations of that rule in source packages? One way is to update the reference to Particular.CodeRules, rename the files to `.cs`, fix the violations, and then rename them back to `.g.cs`. Ugly, but I can't think of anything better. Unless the `.g.cs` exclusion is somehow configurable?

**Comment by danielmarbach** [comment]
I seem to vaguely remember that adding to the file

```
// <auto-generated/>
```

or

```
[CompilerGenerated]
```

would also work. I think there is also this one via the editor config file

https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2019#set-rule-severity-of-multiple-analyzer-rules-at-once-in-an-editorconfig-file

**Comment by adamralph** [comment]
Here's another idea: we leave them named `.cs` in source, and then transform them to `.g.cs` at package creation time.

**Comment by andreasohlund** [comment]
Will this have any impact on the way downstrea`sm exclude certain files eg. https://github.com/Particular/NServiceBus.NHibernate/blob/master/src/NServiceBus.NHibernate.AcceptanceTests/NServiceBus.NHibernate.AcceptanceTests.csproj#L29 ?

**Comment by danielmarbach** [comment]
@andreasohlund all downstream packages using excludes like this need to be adjusted so does the PackageFiles hacks we use

```
  <ItemGroup>
    <_PackageFiles Include="**\*.cs;..\NServiceBus.Core\IdGeneration\CombGuid.cs;..\NServiceBus.Core\Sagas\DefaultSagaIdGenerator.cs">
      <BuildAction>Compile</BuildAction>
      <PackagePath>content\App_Packages\NSB.PersistenceTests\;contentFiles\cs\any\NSB.PersistenceTests\</PackagePath>
    </_PackageFiles>
    <_PackageFiles Remove="**\obj\**\*.cs" />
    <_PackageFiles Remove="PersistenceTestsConfiguration.cs" />
  </ItemGroup>
```

@adamralph do you think the package files target supports that kind of proposed transformation?

**Comment by danielmarbach** [comment]
ok found it out. It works like a charm. I'll update the PR as an example

**Comment by danielmarbach** [comment]
image

**Comment by danielmarbach** [comment]
and then if the file has any violation locally the build fails locally becaue the local file is still `.cs`

**Comment by adamralph** [comment]
👍 lovely! 👌

**Pull request closed without merging**
