### PR TITLE
Patch 7.2.1

### PR DESCRIPTION
**Pull request by andreasohlund**
Contains the following fixes:

* https://github.com/Particular/NServiceBus/pull/5554
* https://github.com/Particular/NServiceBus/pull/5488

### CODE REVIEW

**Comment by andreasohlund** [comment]
@bording added you as a reviewer since I've pulled in the C# 8 nullable fix that you were involved with (wished I would have squashed the PR when that one was merged :( )

**Comment by timbussmann** [comment]
why not two separate PRs so the release notes will make more sense?

**Comment by bording** [comment]
> why not two separate PRs so the release notes will make more sense?

I think this does make more sense, and should work fine with getting the correct versioning, etc.

**Comment by andreasohlund** [comment]
Its the individual PRs that is assigned to the milestone so this approach doesn't affect the release notes

**Comment by timbussmann** [comment]
> Its the individual PRs that is assigned to the milestone so this approach doesn't affect the release notes

ok that makes sense 👍 

> I think this does make more sense, and should work fine with getting the correct versioning, etc.

I still don't understand why a separate PR would be necessary (or better) instead of merging two dedicated PRs for two unrelated changes? There should be no issues to versioning by using 2 PRs or am I missing something?

However, given the milestones are set correctly on the related issues, that doesn't seem to be blocker.

**Pull request merged**
