### PR TITLE
use CreateAsyncScope

### PR DESCRIPTION
**Pull request by SimonCropp**
Is there any reason we are not using async scopes?

### CODE REVIEW

**Comment by danielmarbach** [comment]
@SimonCropp thanks for bringing this up.

We have to do a bit more of triaging but I think this is an actual bug. I added an acceptance test to verify the behavior to https://github.com/Particular/NServiceBus/pull/6650 with a cherry pick of your commit here.

The test fails and makes the endpoint actually not receive any messages as soon as a scoped `IAsyncDisposable` is registered. Unfortunately, I will be soon leaving for Christmas vacation, but I'm sure someone else can take this over.

**Comment by danielmarbach** [comment]
Closing in favor of https://github.com/Particular/NServiceBus/pull/6650. Your commit has been cherry picked there! Thanks :1st_place_medal:

**Comment by danielmarbach** [comment]
@SimonCropp [8.0.3 has been released](https://discuss.particular.net/t/nservicebus-8-0-3-patch-release-available/3355) with the fixes from #6650

**Comment by SimonCropp** [comment]
@danielmarbach awesome. thanks

**Pull request closed without merging**
