### PR TITLE
Circuit breaker timeout fix for 5.2.x

### PR DESCRIPTION
**Pull request by ramonsmits**

### CODE REVIEW

**Comment by ramonsmits** [comment]
@indu @colin-higgins can you please squash those cleanups?

**Comment by ramonsmits** [comment]
Can't we remove that magic number? Move the TimeSpan.FromMinutes to a field with the name TimeoutStorageCircuitBreakerDurationDefault?

**Comment by ramonsmits** [comment]
@colin-higgins Not a huge improvement to extract the value but I like to put such values in const or static readonly fields. The benefit is that you can add xml doco.

**Comment by colin-higgins** [comment]
@ramonsmits Okay, I will pull it out into a field. A separate commit is good for that right? It's logically different.

**Comment by ramonsmits** [comment]
Its a different change so separate commit is fine.

**Pull request merged**
