### PR TITLE
A couple async spots that don't need a state machine

### PR DESCRIPTION
**Pull request by DavidBoike**
Didn't want to add these to #3756

### CODE REVIEW

**Comment by andreasohlund** [comment]
LGTM

**Comment by danielmarbach** [comment]
See https://github.com/Particular/NServiceBus/pull/3727 and will potentially not work because of missing variance.

:-1:

**Comment by DavidBoike** [comment]
And acceptance tests were rampantly timing out. Can't blindly follow AsyncFixer it appears. Closing this one.

**Comment by andreasohlund** [comment]
ugh, async is tricky shit!!! Thanks @danielmarbach

**Pull request closed without merging**
