### PR TITLE
Move startup diagnostics feature to hosting component

### PR DESCRIPTION
**Pull request by andreasohlund**

### CODE REVIEW

**Comment by SimonCropp** [comment]
note that this a is a breaking change. since currently the only way to access them programmatically is to use ` settings.Get<StartupDiagnosticEntries>();` https://github.com/Particular/NServiceBus/issues/5159#issuecomment-388699154

**Comment by SeanFeldman** [comment]
@SimonCropp how come? `StartupDiagnosticEntries` is still found in the `SettingsHolder` and https://github.com/Particular/NServiceBus/issues/5159#issuecomment-388699154 will work as expected.

**Comment by SimonCropp** [comment]
@SeanFeldman sorry. u r correct. i saw the line that removed it from the settings but not the new location that it was added.

**Comment by SeanFeldman** [comment]
No worries. Always good to have an extra check 🙂

**Pull request merged**
