### PR TITLE
Adding GetDestination extension method for sendoptions

### PR DESCRIPTION
**Pull request by mat-mcloughlin**
Relates to https://github.com/Particular/NServiceBus/pull/3473

@timbussmann is working on adding in more options getters but whilst he's away I'm just adding in the ones required to get the testing framework migrated to v6

### CODE REVIEW

**Comment by danielmarbach** [comment]
@mat-mcloughlin @hmemcpy Sorry this PR hasn't been reviewed by anyone from the @Particular/nservicebus-maintainers group. At least I couldn't find any evidence of it. I reverted the PR on develop

**Comment by danielmarbach** [comment]
@mat-mcloughlin the branch is still there. You can rebase on develop and open up a new PR and ping @Particular/nservicebus-maintainers

**Comment by mat-mcloughlin** [comment]
Sorry guys. Didn't realise the PR's need reviewing specifically by a maintainer. Wont happen again :(

**Comment by danielmarbach** [comment]
@hmemcpy No problem.

**Pull request merged**
