### PR TITLE
Reproduce scanner issue where messages can't be detected during scanning

### PR DESCRIPTION
**Pull request by andreasohlund**
Repro for https://github.com/Particular/NServiceBus/issues/4634

### CODE REVIEW

**Comment by andreasohlund** [comment]
@Particular/nservicebus-maintainers @danielmarbach as discussed, test included but ignored and issue raised to track the issue

**Comment by bording** [comment]
@andreasohlund Why add a test just to prevent it from running? If I'm understanding correctly, this feels like it should have been another failing test introduced in #4615 since that's the change for 6.3 that makes this pass, correct?

If so, why not just add it now and have it run?

**Comment by andreasohlund** [comment]
> If I'm understanding correctly, this feels like it should have been another failing test introduced in #4615 since that's the change for 6.3 that makes this pass, correct?

Not correct, #4615 makes this work by discovering the message type as the message is received. This bug is still there, the message is missed during scanning.

@danielmarbach wan't to keep the changes to the asm testing code so I felt that the test was good to show how to exercise the code but I guess I could just remove it?

**Comment by bording** [comment]
@andreasohlund OK I see how #4615 was the workaround solution vs. fixing the exact scenario this test demonstrates.

Do we ever intend to make a change where this test would pass? If we think this won't be changed and this test would never pass, I'm not sure I see the benefit of adding a test that we have to maintain that will always fail if we run it.

If it is worth having this around in some capacity, I'd prefer to have the test swapped around so that it can run and pass, documenting that we actually expect this to fail.

**Comment by andreasohlund** [comment]
I like the swapping of the assert to keep it running

**Comment by timbussmann** [comment]
I'm with @bording on changing the test in a way that it always runs. 👎 on adding more `Explicit` tests.

**Comment by andreasohlund** [comment]
I made the test always run now as requested

**Comment by andreasohlund** [comment]
@timbussmann should be good to go now

**Comment by bording** [comment]
@andreasohlund Should the comment about the assert mention that the test name should also be changed when the assert changes?

**Comment by andreasohlund** [comment]
@bording good catch, updated

**Pull request merged**
