### PR TITLE
Exclude self verification tests from source ATT nuget

### PR DESCRIPTION
**Pull request by andreasohlund**
Fixes https://github.com/Particular/NServiceBus/issues/4762

### CODE REVIEW

**Comment by bording** [comment]
@andreasohlund Instead of adding another item to the Exclude list, would it make more sense to move these tests under the Core folder?

Also, are we sure that all of the verification tests aren't useful for downstreams?

**Comment by andreasohlund** [comment]
>Instead of adding another item to the Exclude list, would it make more sense to move these tests under the Core folder?

I felt that the separate folder was more intention revealing?


>Also, are we sure that all of the verification tests aren't useful for downstreams?

I considered https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.AcceptanceTests/ConventionEnforcementTests.cs#L12 but since we now have explicit cleanup there is not harm skipping this.

In short: No

**Comment by dbelcham** [comment]
When @timbussmann and I have been reviewing tests, our practice has been to move the tests that don't need to go to downstreams into the /Core folder. In this case I think we would have moved them to /Core/SelfVerification

**Comment by andreasohlund** [comment]
My thinking was:

 `/Core` - Tests only relevant for core

`SelfVerification` - Tests that checks conventions etc across all tests in the csproj

But I'm not religious, happy to just move them all to /core?

**Comment by dbelcham** [comment]
I'm going to pull back on the thought that these belong in `/Core`.  They don't seem like they're testing Core functionality, but instead are testing the tests.

So my thoughts now are if there is the chance that any tests in downstreams would benefit from these checks. i.e. would there be any tests in the NHibernate persistence, that don't exist in the ATT suite, that would benefit from being checked for virtual saga properties? I'm guessing that there aren't.

**Comment by andreasohlund** [comment]
>I'm going to pull back on the thought that these belong in /Core. They don't seem like they're testing Core functionality, but instead are testing the tests.

Agreed, I'd extend this to say that they are verifying that we don't ship tests to downstreams that are broken in the downstream context (eg. sagas with non virtual properties)

>So my thoughts now are if there is the chance that any tests in downstreams would benefit from these checks. i.e. would there be any tests in the NHibernate persistence, that don't exist in the ATT suite, that would >benefit from being checked for virtual saga properties? I'm guessing that there aren't.

Completely agree, the ROI is checking in core to not ship broken stuff. When you are writing your own tests in eg NHIbernate fixing those sagas to have virtual properties are trivial.

In short: I don't see any need to ship these types of tests 


Let's go ahead and merge this PR?

**Comment by dbelcham** [comment]
Talked with @bording about this before merging it and we think that some of these might have value downstream...but we need to investigate them. The current idea is to note the tests raised here in #4457 so that they are explicitly and thoroughly addressed in that review process.

**Pull request closed without merging**
