### PR TITLE
support structs in json

### LINKED ISSUE #3650: `ArgumentNullException` when sending struct
Found In Version 5

If I have a message type that is a `struct`, the call to `Bus.Send()` results in an `ArgumentNullException` with this stack trace

```
at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
at NServiceBus.Unicast.Messages.MessageMetadataRegistry.GetMessageMetadata(Type messageType) in c:\BuildAgent\work\1b05a2fea6e4cd32\src\NServiceBus.Core\Unicast\Messages\MessageMetadataRegistry.cs:line 33
at NServiceBus.Unicast.Messages.LogicalMessageFactory.Create(Type messageType, Object message, Dictionary`2 headers) in c:\BuildAgent\work\1b05a2fea6e4cd32\src\NServiceBus.Core\Unicast\Messages\LogicalMessageFactory.cs:line 74
at NServiceBus.Unicast.Messages.LogicalMessageFactory.Create(Object message) in c:\BuildAgent\work\1b05a2fea6e4cd32\src\NServiceBus.Core\Unicast\Messages\LogicalMessageFactory.cs:line 45
at NServiceBus.Unicast.UnicastBus.Send(Object message) in c:\BuildAgent\work\1b05a2fea6e4cd32\src\NServiceBus.Core\Unicast\UnicastBus.cs:line 463

```

`LogicalMessageFactory` checks to ensure that the message type is not `null` and then runs the type through `IMessageMapper` before trying to get the message metadata. `IMessageMapper` is converting the message type to null. 

If struct messages are supported then this is a bug.
If struct messages are not supported then a better error message (perhaps when the `MessageMapper` is first initialized) would be helpful.

### PR DESCRIPTION
**Pull request by SimonCropp**
fixes #3650

### CODE REVIEW

**Comment by SimonCropp** [comment]
figured this would be easier than documenting it

**Comment by timbussmann** [comment]
> figured this would be easier than documenting it

shouldn't we then also document & test that structs are supported?

**Comment by timbussmann** [comment]
@SimonCropp any updates on this?

**Comment by SimonCropp** [comment]
nah i hit the rabbit hole of the message mapper. dont think this can be fixed in the v6 timeframe. will revisit after v6

**Pull request closed without merging**
