### PR TITLE
Fixing mentioning of bus in best practices validation

### PR DESCRIPTION
**Pull request by danielmarbach**
Closes https://github.com/Particular/NServiceBus/issues/4083

### CODE REVIEW

**Comment by danielmarbach** [comment]
@Particular/nservicebus-maintainers please review

**Comment by SzymonPobiega** [comment]
@danielmarbach please take a look if the messages here http://docs.particular.net/nservicebus/messaging/messages-events-commands are sill valid

**Comment by danielmarbach** [comment]
@SzymonPobiega no they are not. I wanted to wait for the review and then update the messages

**Comment by SzymonPobiega** [comment]
:+1:

**Comment by SzymonPobiega** [comment]
@danielmarbach I can change them. I am adding my messages there.

**Comment by SzymonPobiega** [comment]
I included this changes in my pull https://github.com/Particular/docs.particular.net/pull/1836

**Comment by danielmarbach** [comment]
Thanks!

**Pull request merged**
