### PR TITLE
Delivery constraint extensions bug

### PR DESCRIPTION
**Pull request by SeanFeldman**
Comparison should be based on inheritance, not equality.
@Particular/nservicebus please review

### CODE REVIEW

**Comment by danielmarbach** [comment]
Can you elaborate the reasoning behind this change? In general it should be an exact match. The only thing I could come up with was DelayedDeliveryConstraint.

**Comment by SeanFeldman** [comment]
Absolutely.

image

ASB transport supports `DelayDeliveryWith` and `DoNotDeliverBefore` constraints. The base `DelayedDeliveryConstraint` on it's own make no sense to be returned from the [`TransportDefinition`](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/develop/src%2FTransport%2FConfig%2FAzureServiceBusTransport.cs#L49).

Example: when `TimeoutManager` checks if delayed delivery can be supported, it should do that based on constraints supported by the transport, and not general constraint used [for querying](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/DelayedDelivery/RouteDeferredMessageToTimeoutManagerBehavior.cs#L25) if constrains are of type `DelayedDeliveryConstraint` similar to the code [below](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/DelayedDelivery/RouteDeferredMessageToTimeoutManagerBehavior.cs#L54)

```c#
DelayedDeliveryConstraint constraint;
context.TryGetDeliveryConstraint(out constraint)

DateTime deliverAt;
var delayConstraint = constraint as DelayDeliveryWith;

if (delayConstraint != null)
{
   deliverAt = DateTime.UtcNow + delayConstraint.Delay;
}
else
{
   deliverAt = ((DoNotDeliverBefore)constraint).At;
}
```

**Comment by SeanFeldman** [comment]
PS: when implementing [`TransportDefinition.GetSupportedDeliveryConstraints`](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Transports/TransportDefinition.cs#L30), it shouldn't return specific constraints, not the abstract used to group those together. [ASB example](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/develop/src/Transport/Config/AzureServiceBusTransport.cs#L50-L52)

**Comment by SeanFeldman** [comment]
@danielmarbach have also discussed this with @andreasohlund and @yvesgoeleven. Please chime in.

**Comment by danielmarbach** [comment]
If you have consent with them feel free to move on with it. Didn't have
time today

On Wednesday, December 9, 2015, Sean Feldman <notifications@github.com>
wrote:

> @danielmarbach <https://github.com/danielmarbach> have also discussed
> this with @andreasohlund <https://github.com/andreasohlund> and
> @yvesgoeleven <https://github.com/yvesgoeleven>. Please chime in.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/NServiceBus/pull/3181#issuecomment-163356871>
> .
>


-- 
*#NSBcon 2015 • The "All About NServiceBus" conference is back *
*• Learn more <http://go.particular.net/l/27442/2015-08-21/5d4wzp> →*

**Comment by SeanFeldman** [comment]
@danielmarbach don't want to commit my own PR :)

**Comment by danielmarbach** [comment]
Andreas did it for you

On Wednesday, December 9, 2015, Sean Feldman <notifications@github.com>
wrote:

> @danielmarbach <https://github.com/danielmarbach> don't want to commit my
> own PR :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/NServiceBus/pull/3181#issuecomment-163360000>
> .
>


-- 
*#NSBcon 2015 • The "All About NServiceBus" conference is back *
*• Learn more <http://go.particular.net/l/27442/2015-08-21/5d4wzp> →*

**Comment by SeanFeldman** [comment]
Thank you @andreasohlund :)

**Pull request merged**
