### PR TITLE
Add subscription behavior acceptance test

### PR DESCRIPTION
**Pull request by timbussmann**
Connects to Particular/V6Launch#68

Tests that we send a subscription message to each instance of a logical endpoint and that we do not use a distribution strategy.

@Particular/nservicebus-maintainers @SzymonPobiega @DavidBoike please review

### CODE REVIEW

**Comment by DavidBoike** [comment]
Wait, what? I'm not getting something.

If a publisher is scaled out, why would *both* instances receive a subscription request?

**Comment by bording** [comment]
Only scenario I can think of where you'd want this would be if each instance had their own persistence db instead of sharing. 

When would it make sense to do that, though? Seems like it would lead to some odd situations, especially if you weren't sharing timeout storage.

**Comment by timbussmann** [comment]
> Wait, what? I'm not getting something.

my firsts thoughts too, but talking to @SzymonPobiega:

> I think sending to every instance is a better strategy because it allows the cluster to not share subscription storage. They are defuplicated anyway by design.

but currently I just wanted to "document" and verify that behavior, I'm perfectly fine to discuss this, but then let's raise an issue and not extend on this PR?

**Comment by timbussmann** [comment]
> allows the cluster to not share subscription storage

is a probably quite tricky, since at least saga storage should be shared anyway, so we could argue this is not supported for now and change the behavior. But again, that should be discusses somewhere else.

**Comment by timbussmann** [comment]
@Particular/nservicebus-maintainers any concerns to merge this?

**Comment by danielmarbach** [comment]
I agree with @timbussmann the discussion should be raised in. sep. Issue. This test verifies the current behavior therefore ok to merge

**Pull request merged**
