### PR TITLE
Passing critical error into init

### PR DESCRIPTION
**Pull request by yvesgoeleven**
so that all callbacks can be initialized in the same place when implementing a transport

### CODE REVIEW

**Comment by SimonCropp** [comment]
cant u access CriticalError  from the container?

**Comment by yvesgoeleven** [comment]
@SimonCropp no, transports do not have access to the container anymore

**Comment by SimonCropp** [comment]
so u cant do it the same way msmq does https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Transports/Msmq/Msmq.cs#L49  ?

**Comment by SimonCropp** [comment]
sorry ignore that. i see what u r doing

**Comment by yvesgoeleven** [comment]
How does this API Approval thingy (which fails) work?

**Comment by SimonCropp** [comment]
@yvesgoeleven if u run this in debug it will place an approval command in the clipboard https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core.Tests/API/APIApprovals.cs

**Comment by yvesgoeleven** [comment]
@SimonCropp thanks, replaced the approved file with received file (assuming that's what needs to be done to accept the api change). Build pending

**Comment by SimonCropp** [comment]
yeah that is correct. the command line placed in the clipboard when running the test does just that

**Comment by yvesgoeleven** [comment]
All tests passed, if anyone would be willing to merge it into the core that would be much appreciated

**Pull request merged**
