### PR TITLE
Delayed delivery checks

### PR DESCRIPTION
**Pull request by timbussmann**
addresses https://github.com/Particular/NServiceBus/issues/4541

The first commit contains checks on the SendOptions extensions which prevent users to use both options on the same option. However, it doesn't prevent anyone from adding the constraint back into the constraints collection later on.

There doesn't seem to be a good single spot to inspect the constraints collection in core directly. So commit no. 2 contains a new transport test which verifies that transports inspect the constraints and throw. I'm not sure we really want to do that though:
* It requires specific logic to check those constraints in every transport against each other.
* It requires the transport to throw a meaningful exception text which is a poor contract to implement.

thoughts @Particular/nservicebus-maintainers ?

### CODE REVIEW

**Comment by andreasohlund** [comment]
@danielmarbach would you say that the send options check plugs the hole mentioned in https://github.com/Particular/NServiceBus/issues/4541 ?

**Comment by danielmarbach** [comment]
Looks like for me but I haven't look deep into the details of this PR.

**Comment by timbussmann** [comment]
we discussed commit no. 2 on today's daily sync and agreed that we think the issue is address good enough with the checks on the delayed delivery extensions.

@bording brought up the idea of verifying all transports apply the same order in case somebody adds an additional constraints in the pipeline instead of expecting an exception. This would make the tests and the API definitely nicer, but we think it would be too difficult to verify whether a transport used the right option from a transport test. Brandon mentioned he did already verify that all transports behave the same a while ago.

**Comment by timbussmann** [comment]
reverted commit no.2. This is ready to go @Particular/nservicebus-maintainers

**Pull request merged**
