### PR TITLE
[WIP] Message handling contexts

### PR DESCRIPTION
**Pull request by danielmarbach**
Based on #2669 

- [ ] Design, discuss and implement mutator API (does it need contextual bus?)
 (see here https://github.com/Particular/NServiceBus/commit/47c161da195e9a2505354e068a5d5590c7250f4d)
- [ ] Design, discuss and implement contexts
- [ ] Design, discuss and implement SagaNotFound context (see here https://github.com/Particular/NServiceBus/commit/1ab75728b109bd14a9463c68ed7003048d9b1e32)
- [ ] Design, discuss and implement potentially missing contexts (started discussion see https://github.com/Particular/NServiceBus/pull/2669#issuecomment-88426656)

### CODE REVIEW

**Comment by danielmarbach** [comment]
@johnsimons @andreasohlund @SzymonPobiega which of those interfaces needs also a contextual overload (new style API)?

- [ ] NServiceBus.IResponse (new API)
- [ ] NServiceBus.IManageMessageHeaders
- [ ] NServiceBus.INeedInitialization
- [ ] NServiceBus.ISendOnlyBus
- [ ] NServiceBus.IDataBusProperty
- [ ] NServiceBus.IWantToRunBeforeConfigurationIsFinalized
- [ ] NServiceBus.ISpecifyMessageHandlerOrdering
- [ ] NServiceBus.IAuthorizeSubscriptions
- [ ] NServiceBus.IBus
- [ ] NServiceBus.ICallback
- [ ] NServiceBus.IMessage
- [ ] NServiceBus.ICommand
- [ ] NServiceBus.IEvent
- [ ] NServiceBus.IMessageContext
- [ ] NServiceBus.IMessageCreator
- [X] NServiceBus.IHandleMessages<T>
- [ ] NServiceBus.IProcessEvents<T>
- [ ] NServiceBus.IEventContext (new API)
- [ ] NServiceBus.IProcessCommands<T> (new API)
- [ ] NServiceBus.ICommandContext (new API)
- [ ] NServiceBus.IProcessResponses<T> (new API)
- [ ] NServiceBus.IResponseContext (new API)
- [ ] NServiceBus.IStartableBus
- [X] NServiceBus.IWantToRunWhenBusStartsAndStops
- [ ] NServiceBus.IRunWhenBusStartsAndStops (new API)
- [ ] NServiceBus.IRunContext (new API)
- [ ] NServiceBus.IConfigureThisEndpoint
- [ ] NServiceBus.IExcludesBuilder
- [ ] NServiceBus.IIncludesBuilder
- [ ] NServiceBus.DataBus.IDataBusSerializer
- [ ] NServiceBus.DataBus.IDataBus
- [ ] NServiceBus.Logging.ILog
- [ ] NServiceBus.Logging.ILoggerFactory
- [ ] NServiceBus.Saga.IConfigureHowToFindSagaWithMessage
- [ ] NServiceBus.Saga.IContainSagaData
- [X] NServiceBus.Saga.IAmStartedByMessages<T>
- [X] NServiceBus.Saga.IAmStartedByCommands<T> (new API)
- [X] NServiceBus.Saga.IAmStartedByEvents<T> (new API)
- [ ] NServiceBus.Saga.IFinder
- [ ] NServiceBus.Saga.IFindSagas<T>+Using<M>
- [X] NServiceBus.Saga.IHandleSagaNotFound
- [ ] NServiceBus.Saga.IProcessSagaNotFound (new API)
- [ ] NServiceBus.Saga.ISagaNotFoundContext
- [X] NServiceBus.Saga.IHandleTimeouts<T>
- [ ] NServiceBus.Saga.IProcessTimeouts<T> (new API)
- [ ] NServiceBus.Saga.ITimeoutContext (new API)
- [ ] NServiceBus.Saga.ISagaPersister
- [ ] NServiceBus.Serialization .IMessageSerializer
- [ ] NServiceBus.Satellites.ISatellite
- [ ] NServiceBus.Satellites.IAdvancedSatellite
- [ ] NServiceBus.Installation.INeedToInstallSomething
- [X] NServiceBus.MessageMutator .IMutateOutgoingMessages
- [X] NServiceBus.MessageMutator .IMutateIncomingMessages
- [X] NServiceBus.MessageMutator .IMessageMutator
- [ ] NServiceBus.MessageMutator .IMutateOutgoingMessage (new API)
- [ ] NServiceBus.MessageMutator .IMutateIncomingMessage (new API)
- [ ] NServiceBus.MessageMutator .IMessagesMutator (new API)
- [ ] NServiceBus.MessageMutator .IMutateIncomingMessageContext (new API)
- [X] NServiceBus.MessageMutator .IMutateIncomingTransportMessages
- [ ] NServiceBus.MessageMutator .IMutateIncomingTransportMessage
- [ ] NServiceBus.MessageMutator .IMutateIncomingTransportMessageContext (new API)
- [ ] NServiceBus.MessageMutator .IMutateOutgoingMessageContext (new API)
- [X] NServiceBus.MessageMutator .IMutateOutgoingTransportMessages
- [ ] NServiceBus.MessageMutator .IMutateOutgoingTransportMessage (new API)
- [ ] NServiceBus.MessageMutator .IMutateOutgoingTransportMessageContext (new API)
- [X] NServiceBus.MessageMutator .IMutateTransportMessages
- [ ] NServiceBus.MessageMutator .IMutateTransportMessage (new API)
- [ ] NServiceBus.Outbox.IOutboxStorage
- [X] NServiceBus.UnitOfWork.IManageUnitsOfWork (@danielmarbach added this one, not yet done)
- [ ] NServiceBus.Config.IWantToRunWhenConfigurationIsComplete
- [ ] NServiceBus.Config.ConfigurationSource .IConfigurationSource
- [ ] NServiceBus.Config.ConfigurationSource .IProvideConfiguration<T>
- [ ] NServiceBus.Pipeline.IBehavior<TIn,TOut>
- [ ] NServiceBus.Pipeline.IStageConnector
- [ ] NServiceBus.Pipeline.IExecutor
- [ ] NServiceBus.Pipeline.PipelineFactory
- [ ] NServiceBus.Encryption .IEncryptionService
- [ ] NServiceBus.Faults .IManageMessageFailures
- [ ] NServiceBus.Settings.ReadOnlySettings
- [ ] NServiceBus.Gateway.Deduplication .IDeduplicateMessages
- [ ] NServiceBus.MessageInterfaces .IMessageMapper
- [ ] NServiceBus.Unicast.IMessageHandlerRegistry
- [ ] NServiceBus.Unicast.Subscriptions .MessageDrivenSubscriptions .ISubscriptionStorage
- [ ] NServiceBus.Unicast.Queuing .IWantQueueCreated
- [ ] NServiceBus.ObjectBuilder.Common .IContainer
- [ ] NServiceBus.Timeout.Core .IPersistTimeouts


Should we support custom context in `IFindSagas`, `IManageUnitOfWork`?

**Comment by andreasohlund** [comment]
@danielmarbach what do we do with this one?

**Comment by danielmarbach** [comment]
You can close. Might be beneficial to copy the list as a potential reference for "might need context" discussions

**Comment by andreasohlund** [comment]
@timbussmann can you extract the list into your pull/todo/whatever?

**Comment by timbussmann** [comment]
@andreasohlund copies to https://github.com/Particular/PlatformDevelopment/issues/187

**Pull request closed without merging**
