### PR TITLE
Making context.Trace thread safe

### PR DESCRIPTION
**Pull request by johnsimons**
As currently stands the trace can be overrided by competing threads

### CODE REVIEW

**Comment by johnsimons** [comment]
@Particular/nservicebus-maintainers review at your own convenience

**Comment by danielmarbach** [comment]
Can you do a quick format?

I prefer to use string.Join instead if String.Join

**Comment by johnsimons** [comment]
@danielmarbach I prefer the opposite :wink:

**Comment by danielmarbach** [comment]
Should I play my "I'm in the maintainer group" card ;)?

**Comment by danielmarbach** [comment]
Anyhow, can you do the code cleanup

**Comment by johnsimons** [comment]
I'm confused, what is wrong with the format?

**Comment by johnsimons** [comment]
@danielmarbach I have just ran the:
image
and no further changes, what am I doing wrong ?

**Comment by danielmarbach** [comment]
Sorry my bad. I checked it out and saw that it is all clean. Because of the LogItem I figured there is more in that class and felt the field needs to move down.

**Comment by danielmarbach** [comment]
Merged https://github.com/Particular/NServiceBus/commit/4dfc45b7c09294d34ade2842cb195e9d0c767e40

**Comment by johnsimons** [comment]
But but I didn't even had to bribe you!

**Comment by johnsimons** [comment]
I was ready for it :smile:

**Pull request closed without merging**
