### PR TITLE
Simplify the handle ordering API

### PR DESCRIPTION
**Pull request by johnsimons**
### Problem description
At the moment we have a very IMO unintuitive API to specify message ordering.
1. The user needs to implement `ISpecifyMessageHandlerOrdering`, eg 
```c#
class EnsureOrdering : ISpecifyMessageHandlerOrdering
{
    public void SpecifyOrder(Order order)
    {
        order.Specify(First<H1>.Then<H2>());
    }
}
```
2. The user can also specify order via the `config.LoadMessageHandlers` overloads, eg:
```c#
config.LoadMessageHandlers(First<H1>.Then<H2>().AndThen<H3>().AndThen<H4>())
```

### Proposal
- [x] Deprecate all the above API;
- [x] Introduce a new simple api to specify ordering;
- [x] Doco (see https://github.com/Particular/docs.particular.net/pull/707)

#### New API
```c#
config.ExecuteTheseHandlersFirst(params Type[] handlerTypes)
```

### CODE REVIEW

**Comment by johnsimons** [comment]
@Particular/nservicebus this one is ready to be reviewed.
Not sure about the proposed method names ?

**Comment by danielmarbach** [comment]
@johnsimons How can we proceed with this? I think the method names are good.

**Comment by johnsimons** [comment]
@danielmarbach a bit busy with the SC retries, but all is left is merge and doco

**Comment by danielmarbach** [comment]
@johnsimons Decided to get rid of the `IEnumerable` overload because when you do this:

image

The compiler chooses the params overload and then Resharper says your definition is redundant.

   var handlerTypes = new []{ typeof(Saga1), typeof(Saga2)};
   c.ExecuteTheseHandlersFirst(handlerTypes);

picks also the params overload

When you want to pass in an `IEnumerable` it is low friction to just call `ToArray()` like this

                    var handlerTypes = new List<Type>{ typeof(Saga1), typeof(Saga2)};
                    c.ExecuteTheseHandlersFirst(handlerTypes.ToArray());

One less public API is good.

**Comment by danielmarbach** [comment]
@johnsimons hold your breath. I did a rebase.

**Comment by danielmarbach** [comment]
@johnsimons I did the doco. Please chime in for the review here https://github.com/Particular/docs.particular.net/pull/707

**Comment by SimonCropp** [comment]
Disagree. If u only do one method u shoud do the ienumerable one.

**Comment by danielmarbach** [comment]
@SimonCropp provide more context please. If not your reasoning cannot be understood.

**Comment by SimonCropp** [comment]
@danielmarbach the standard approach for taking in multiple items in an api is IEnumerable. i dont see a reason to deviate from that.

as for

> One less public API is good.

While i agree with that in principle i dont think it applies in this case. i cant think of a scenario where we would change this api in a way that would cause extra pain to the consumer because we are taking the standard approach of  "param and a enumerable overload". Effectively, in this case, it is one api with two manifestations for convenience. So i think leave it with a params and enumerable

**Comment by danielmarbach** [comment]
Yeah but did you read my comment how it looks from the usage perspective?

I don't feel strong about it. You have more experience with those sort of APIs than I have. I just felt weird when coding against the API. Based on that hunch I removed the enumerable overload.

**Comment by SimonCropp** [comment]
@danielmarbach i am confused

the regular use of this api is to pass in a small number of types known at compile time. so the usage would not be 

       c.ExecuteTheseHandlersFirst(new []{ typeof(Saga1), typeof(Saga2)});

but 

       c.ExecuteTheseHandlersFirst(typeof(Saga1), typeof(Saga2));

**Comment by danielmarbach** [comment]
Ergo we don't need the enumerable overload ;)

**Comment by SimonCropp** [comment]
there is not tax in this extra api https://github.com/Particular/NServiceBus/pull/2280#issuecomment-122342070

and there is some benefit. ie no need for a toarray. ergo we should have both

**Comment by johnsimons** [comment]
@danielmarbach the only reason I added the `IEnumerable` overload was so that if the user already has an enumeration of handler types, they can just pass that in, eg:
```c#
IEnumerable<Type> handlersToExecuteFirst = GetListOfHandlers();
c.ExecuteTheseHandlersFirst(handlersToExecuteFirst);
```
This way there is no need to allocate an extra array.

Does this make sense ?

Also in your example, R# is just suggesting an optimisation based on static code analysis, and yes in that specific case it makes sense to do what R# suggests, but in the example above there is no optimisation.

**Comment by danielmarbach** [comment]
@johnsimons @SimonCropp reverted back to have both APIs.

**Pull request merged**
