### PR TITLE
Finalizing top level API revamp

### PR DESCRIPTION
**Pull request by SzymonPobiega**
* `IBusContext` -> `ICommunicationSession`
 * `IBusInterface` -> `ICommunicationSessionFactory`
 * `IEndpoint` -> `IEndpointInstance`
 * `BusConfiguration` -> `EndpointConfiguration`

### CODE REVIEW

**Comment by SzymonPobiega** [comment]
@Particular/nservicebus @Particular/tf-asyncawait @indualagarsamy  please review these changes (if they align with the discussion we had)

**Comment by andreasohlund** [comment]
I have a faint memory that we decided to keep `BusConfiguration` and `Bus.Create` to not rock the boat to much and `var endpointInstance = Bus.Create(config)`reads ok to me?`

**Comment by timbussmann** [comment]
tbh I don't like `ICommunicationSession`. ICommunicationSession.Send/Publish/etc... just doesn't sound correct. I'd prefer `IBusSession` any time.

**Comment by SzymonPobiega** [comment]
@timbussmann we decided to not use *the B word* in this part.

**Comment by timbussmann** [comment]
seems like I got an amnesia, but reading the argumentation:

> For the usage of IBus outside the scope of message handling we need another concept with avoids the terminology of "bus" in order to make a clear distinction between what is used outside the scope of message handling (i.e. MvcController, NancyModules, Console Applications) and the context inside the scope of message handling.

It's not clear to me, why `IBusSession` isn't obvious about the context it's used from?
* Within the pipeline we float the current session which has been opened/started by the transport when receiving an incoming message
* Outside the pipeline, you use whatever session the user has created at some point using `CreateBusSession` or similar.

IBusSession (or whatever naming) represents a scoped interaction with whatever we call it (but apparently, according to the wiki definition david posted in the linked issue, bus pretty much hits the spot) which allows to Send/Publish/... messages to that thing. 

Please help me out here to regain my memory why the B word is bad :(

**Comment by danielmarbach** [comment]
@SzymonPobiega I think you forgot half of the things we discussed :D According to my memory we (you and I over slack) agreed that there is probably no way around Bus.

**Comment by SzymonPobiega** [comment]
@danielmarbach so nothing to be changed in `develop`?

**Comment by danielmarbach** [comment]
@SzymonPobiega how about just

 * `IBusInterface` -> `IBusContextFactory`
 * `IEndpoint` -> `IEndpointInstance`

and (if others agree) or leave it out

 * `BusConfiguration` -> `EndpointConfiguration`

**Comment by timbussmann** [comment]
what about `IBusContext` -> `IBusSession`?

> IEndpoint -> IEndpointInstance

do you think that's a useful change from an user perspective?

> BusConfiguration -> EndpointConfiguration

I really liked the suggested BusConfig -> EndpointConfig changes but didn't we discard that to not change the API too much?

**Comment by SzymonPobiega** [comment]
`IEndpoint` -> `IEndpointInstance` is about correctness (having code in sync with doco). As for other changes, I don't have strong opinions. I am fine with what Daniel proposed.

**Comment by andreasohlund** [comment]
>I really liked the suggested BusConfig -> EndpointConfig changes but didn't we discard that to not change the API too much?

I don't see enough value here, you could see it as "the bus config for the endpoint instance to be created"  and that seems to fit with ``var endpointInstance = Bus.Create(busConfig)`


So :+1: for keeping `BusConfiguration`

**Comment by SeanFeldman** [comment]
While `EndpointConfiguration` is more correct than `BusConfiguration`, this will be confusing for those that just got off the `Configure` and started using `BusConfiguration` to find that it's renamed again :)

**Comment by SzymonPobiega** [comment]
So everybody agrees on

 * `IBusContext` -> `IBusContext` (no change)
 * `IBusInterface` -> `IBusContextFactory`
 * `IEndpoint` -> `IEndpointInstance`
 * `BusConfiguration` -> `BusConfiguration` (no change)

?

**Comment by andreasohlund** [comment]
>So everybody agrees on

>IBusContext -> IBusContext (no change)
>IBusInterface -> IBusContextFactory
>IEndpoint -> IEndpointInstance
>BusConfiguration -> BusConfiguration (no change)


:+1:

**Comment by timbussmann** [comment]
:+1: Although I really like `IBusSession` (but it doesn't seem to perfectly fit in right now, so let's stay with context).

**Comment by SzymonPobiega** [comment]
@andreasohlund @danielmarbach @timbussmann rebased and ready to merge

**Pull request merged**
