### PR TITLE
Common ISagaPersister tests

### PR DESCRIPTION
**Pull request by SzymonPobiega**
Added a project containing common test cases for saga persisters. Copied over the test from Raven impl as it has the best coverage

### CODE REVIEW

**Comment by johnsimons** [comment]
@SzymonPobiega what's left to do here?

**Comment by danielmarbach** [comment]
@SzymonPobiega I think it would be good to have the basic assumptions the core has in the core. Great stuff. Is there a way to pull this in?

**Comment by SzymonPobiega** [comment]
It is sooooo old. But if you see value here I can try to resurrect it.

**Comment by andreasohlund** [comment]
@timbussmann you brought this up as well, should we get on a call and decide on a POA for the acceptance tests?

**Comment by timbussmann** [comment]
@andreasohlund I intended to create an issue and discuss/rethink ATT structuring in general.

**Comment by andreasohlund** [comment]
:+1:

**Pull request closed without merging**
