### PR TITLE
More transport message fixes

### PR DESCRIPTION
**Pull request by danielmarbach**
@Particular/nservicebus please review

### CODE REVIEW

**Comment by timbussmann** [comment]
:+1:

**Comment by indualagarsamy** [comment]
The obsolete instructions are not clear. 
As a user that's has the following type of code:

```c#
var message = new TransportMessage();
message.Recoverable = true;
```

The first obsolete tells me I need to use OutgoingMessage. Ok. I change `TransportMessage` to `OutgoingMessage`. But OutgoingMessage doesn't have a property called Recoverable. It also has an obsolete message for the Recoverable. 

So, I change the code to:
```c#
byte[] body = new byte[10];
Dictionary<string, string> headers = new Dictionary<string, string>();
var message = new OutgoingMessage("hello", headers, body);
message.Recoverable = true;
```
 and now the error is: 
```
error CS1061: 'OutgoingMessage' does not contain a definition for 'Recoverable' and no extension method 'Recoverable' accepting a first argument of type 'OutgoingMessage' could be found (are you missing a using directive or an assembly reference?)
```

Perhaps add a Recoverable property to the OutgoingMessage with the requisite Obsolete. 

When a user receives an obsolete message, it should be clear how to change that code, to what to get them unstuck and moving.

**Comment by danielmarbach** [comment]
Good points. The previous obsolete was even more wrong. Pointing around in
circles of obsoletion. I'll try to improve

On Tuesday, November 3, 2015, Indu Alagarsamy <notifications@github.com>
wrote:

> The obsolete instructions are not clear.
> As a user that's has the following type of code:
>
> var message = new TransportMessage();
> message.Recoverable = true;
>
> The first obsolete tells me I need to use OutgoingMessage. Ok. I change
> TransportMessage to OutgoingMessage. But OutgoingMessage doesn't have a
> property called Recoverable. It also has an obsolete message for the
> Recoverable.
>
> So, I change the code to:
>
> byte[] body = new byte[10];
> Dictionary<string, string> headers = new Dictionary<string, string>();var message = new OutgoingMessage("hello", headers, body);
> message.Recoverable = true;
>
> and now the error is:
>
> error CS1061: 'OutgoingMessage' does not contain a definition for 'Recoverable' and no extension method 'Recoverable' accepting a first argument of type 'OutgoingMessage' could be found (are you missing a using directive or an assembly reference?)
>
> Perhaps add a Recoverable property to the OutgoingMessage with the
> requisite Obsolete.
>
> When a user receives an obsolete message, it should be clear how to change
> that code, to what to get them unstuck and moving.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/NServiceBus/pull/3056#issuecomment-153439291>
> .
>


-- 
*#NSBcon 2015 • The "All About NServiceBus" conference is back *
*• Learn more <http://go.particular.net/l/27442/2015-08-21/5d4wzp> →*

**Comment by andreasohlund** [comment]
Needs a rebase

**Comment by danielmarbach** [comment]
I dedicated an [entire section](http://docs.particular.net/nservicebus/upgrades/5to6#deprecated-transportmessage) in the upgrade guide to this. Going to merge when green

**Pull request merged**
