### PR TITLE
Made the setting up of endpoint global header more explicit at config time.

### PR DESCRIPTION
**Pull request by johnsimons**
Create a new config time API to set global headers:
```c#
config.OutgoingHeaders.Add("Foo", "Bar");
```

### CODE REVIEW

**Comment by johnsimons** [comment]
@Particular/nservicebus please review

**Comment by SzymonPobiega** [comment]
:+1:

**Comment by andreasohlund** [comment]
I have a faint memory that we talked about getting rid of the static headers all together? (can't find anything so I'm just double checking)

**Comment by danielmarbach** [comment]
Like. This is maybe a non issue. Just want to understand the reasons behind it: why did you change from `IDictionary` to `Dictionary`?

**Comment by johnsimons** [comment]
no reason @danielmarbach 
Which one should I publicly expose?

**Comment by danielmarbach** [comment]
I’ve been exposing IDictionary. But you rarely ever switch the underlying
implementation. So it could be me doing cargo culture..

**Comment by andreasohlund** [comment]
Also curious how to think here. Since its clearly a "DTO" beeing passed in would the concrete `Dictionary` be more intention revealing?

Is there drawbacks for the user if we use `IDictionary`? (nothing comes to mind)

**Comment by johnsimons** [comment]
Yeah I thought about wrapping the `Dictionary` in a more typed way but then I couldn't come up with a reason to do it.
Also because users are already accustomed to use `Dictionary` for headers, it din;t make sense to make these any different.

**Pull request merged**
