### PR TITLE
[WIP] Update fody

### PR DESCRIPTION
**Pull request by SimonCropp**
These are the netstandard compat versions in prep for NSB v7

 * Fody
 * Janitor
 * Obsolete

### CODE REVIEW

**Comment by timbussmann** [comment]
@SimonCropp is this still WIP?

**Comment by SimonCropp** [comment]
@timbussmann i would like to leave it WIP for a few more days. the changes in fody 2 are significant, and i am still finding minor issues and fixing them. also this will be easy to rebase so no reason to rush because of potential conflicts

**Comment by timbussmann** [comment]
👍

**Comment by andreasohlund** [comment]
@SimonCropp should we get this in now?

**Comment by SimonCropp** [comment]
Not yet. Will get to this next week

**Comment by bording** [comment]
Adding WIP back for now.

**Comment by bording** [comment]
Superseded by #4729

**Pull request closed without merging**
