### PR TITLE
Replace string concatenation with interpolation

### PR DESCRIPTION
**Pull request by danielmarbach**
This replaces string concatenation with string interpolation. It does not address the issue of GC pressure because of strings! We can do this at a later time

@Particular/nservicebus-maintainers please review

### CODE REVIEW

**Comment by bording** [comment]
While I think the string interpolated versions are easier to read, unfortunately it's not really all that helpful on the reducing allocations front. Here's a quick comparison:

```csharp
public class StringAllocTests
{
    string defaultNameSpace;
    string typeName;

    [Setup]
    public void Setup()
    {
        defaultNameSpace = "NServiceBus";
        typeName = "Endpoint";
    }

    [Benchmark]
    public string UseConcat() => defaultNameSpace + "." + typeName;

    [Benchmark]
    public string UseInterpolation() => $"{defaultNameSpace}.{typeName}";

    [Benchmark]
    public string UseStringBuilder()
    {
        var builder = new StringBuilder(defaultNameSpace);

        builder.Append(defaultNameSpace);
        builder.Append(".");
        builder.Append("typeName");

        return builder.ToString();
    }
}
```
```ini

BenchmarkDotNet=v0.9.7.0
OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Core(TM) i7-2600K CPU 3.40GHz, ProcessorCount=8
Frequency=3331180 ticks, Resolution=300.1939 ns, Timer=TSC
HostCLR=MS.NET 4.0.30319.42000, Arch=64-bit RELEASE [RyuJIT]
JitModules=clrjit-v4.6.1080.0

Type=StringAllocTests  Mode=Throughput  

```
           Method |      Median |    StdDev |    Gen 0 | Gen 1 | Gen 2 | Bytes Allocated/Op |
----------------- |------------ |---------- |--------- |------ |------ |------------------- |
        UseConcat |  28.3327 ns | 0.3605 ns |   665.08 |     - |     - |              29.35 |
 UseInterpolation | 132.6312 ns | 1.4278 ns |   737.96 |     - |     - |              32.40 |
 UseStringBuilder | 118.0350 ns | 0.4218 ns | 2,938.00 |     - |     - |             129.52 |

I even included a `StringBuilder` in there, and for small strings, it can be the worst option of all!

**Comment by danielmarbach** [comment]
good stuff @bording I was digging a bit in the source code and stumbled over the concatenation. Read up https://leanpub.com/detectingandsolvingmemoryproblemsinnet but didn't dig deeper which I should have! How about I rename the description and we treat this PR as aligned in our interpolation usage?

**Comment by timbussmann** [comment]
the changes are much better to read than the concatenation, so I'm :+1: despite the potential performance impact.

**Comment by SimonCropp** [comment]
i think @ramonsmits had some arguments against interpolation

**Comment by danielmarbach** [comment]
@SimonCropp I followed that discussion and we haven't made a move into the direction of @ramonsmits proposal. We just had heated debates. So in the meantime I'd say we can merge this one until we come to a conclusion. For example logging has other allocation related problems, since most of our methods define an object[] as params we always pay allocation costs even when we don't use it. But again that is a topic of another discussion.

**Comment by Scooletz** [comment]
@danielmarbach As the code you've been working on is synchronous, would you consider using a `ThreadStatic`ally cached `StringBuilder`? Like the one used by `string.Format` methods (implementation [here](http://referencesource.microsoft.com/#mscorlib/system/text/stringbuildercache.cs)? As string builders would be allocated once, that could really lower the number of allocations.

**Comment by danielmarbach** [comment]
@Scooletz I think it makes sense to address string allocations in general in a separate issue. I realized that I approached it wrong.

**Comment by Scooletz** [comment]
@danielmarbach cc me if you do.

**Pull request closed without merging**
