### PR TITLE
Removed some dead code.

### PR DESCRIPTION
**Pull request by SzymonPobiega**
Do not merge yet

### CODE REVIEW

**Comment by SzymonPobiega** [comment]
This is a one-liner. @Particular/nservicebus-maintainers can you review?

**Comment by hmemcpy** [comment]
This is a relic from my work introducing multi-deserializer support. It's not needed anymore, it seems.
Just as an aside, how does a "default serializer" gets chosen now? Where is that defined?

**Comment by SzymonPobiega** [comment]
Good question @hmemcpy . I don't think the acceptance tests cover that scenario...

**Comment by andreasohlund** [comment]
>Do not merge yet

That's what `[WIP]` means :)

**Comment by SzymonPobiega** [comment]
@andreasohlund wanted to be sure ;)

**Comment by SzymonPobiega** [comment]
@hmemcpy here's the trick: https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Serialization/SerializationFeature.cs#L21

**Comment by SzymonPobiega** [comment]
@Particular/nservicebus-maintainers ok, now it is good for merging.

**Comment by hmemcpy** [comment]
Got it! Kill it with fire :D

**Comment by SzymonPobiega** [comment]
:fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire:

**Comment by danielmarbach** [comment]
The PR desc still say do not merge yet

**Comment by timbussmann** [comment]
YOLO :tada:

**Pull request merged**
