### PR TITLE
Enforce Behavior with interface for contexts

### PR DESCRIPTION
**Pull request by danielmarbach**
With making the behavior context classes public again it is now possible to declare a behavior like this:

```
class MyBehavior : Behavior<IncomingLogicalContext> { }
```

unforuntaly this behavior will never get picked up by the model builder internally. In this PR I'll add a runtime check to verify that behaviors use a interface inherited from `IBehaviorContext`.

### CODE REVIEW

**Comment by danielmarbach** [comment]
@Particular/nservicebus please review carefully

**Comment by SzymonPobiega** [comment]
:+1: . Should I merge @danielmarbach ?

**Comment by danielmarbach** [comment]
@SzymonPobiega pushed a last change. Please review again and merge if green

**Comment by danielmarbach** [comment]
@SzymonPobiega @SimonCropp ready to merge?

**Pull request merged**
