### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### Particular/NServiceBus now has a Chat Room on Gitter

@SimonCropp has just created a chat room. You can visit it here: [https://gitter.im/Particular/NServiceBus](https://gitter.im/Particular/NServiceBus?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/Particular/NServiceBus?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by SimonCropp** [comment]
@Particular/engineers would this be a better mechanism to converse with the community in real time?

**Comment by johnsimons** [comment]
@SimonCropp  Quite possible, but the best people to tell us if is a good idea or not would be the community, so how about pinging the google group?

**Comment by johnsimons** [comment]
@SimonCropp do you want to push this one through requirements ? Or can I close it ?

**Comment by SimonCropp** [comment]
i will push it. u can leave it open

**Pull request closed without merging**
