### PR TITLE
Removed tests which no longer test valid assumptions of the containers

### PR DESCRIPTION
**Pull request by WilliamBZA**
/cc @Particular/container-maintainers

### CODE REVIEW

**Comment by danielmarbach** [comment]
@WilliamBZA doesn't compile ;) I made it `[WIP]`

**Comment by WilliamBZA** [comment]
Mental note: CTRL+SHIFT+S to save including the project file...

Updated

**Comment by danielmarbach** [comment]
https://visualstudiogallery.msdn.microsoft.com/426d520e-06a5-4049-820f-0fcd52ec0270

**Comment by WilliamBZA** [comment]
I expected you to have an answer

**Pull request merged**
