### PR TITLE
Prevent message mutators to be provided via the internal container

### PR DESCRIPTION
**Pull request by andreasohlund**
Related to #4738 

Will fix the mutator sample and add to upgrade guide once merged

### CODE REVIEW

**Comment by andreasohlund** [comment]
Ugh, turns out that lots of out ATT:s use the container to register mutators, will fix

**Comment by timbussmann** [comment]
> Ugh, turns out that lots of out ATT:s use the container to register mutators, will fix

@andreasohlund please note that there should be a few tests which explicitly test the container registration API and you can just remove those.

**Comment by andreasohlund** [comment]
It turns out that since we're still using DI for mutators that is registered via the new `.RegisterMessageMutator(new MyMutator())` API and that makes this a bit trickier. Checking in a startup task would mean that we would force all users, even the ones that have their own external container, to use the new API. This would limit them somewhat since the new API doesn't allow them to inject dependencies into the mutators since we force them to pass an instance of the mutator at config time.

Talking to @timbussmann we decided to instead:

* Fix all our internal code (mostly ATT's) that use the container to use the new API instead
* Fix the doco and samples (at least one sample is using the old way)
* Raise a separate issue to stop registering mutators in DI at all

Closing this PR

**Comment by andreasohlund** [comment]
Issue raised https://github.com/Particular/NServiceBus/issues/4982

**Pull request closed without merging**
