### PR TITLE
Upgrade PublicApiGenerator 7.0.0

### PR DESCRIPTION
**Pull request by danielmarbach**

### CODE REVIEW

**Comment by bording** [comment]
@danielmarbach Since this isn't critical to get into 7.0, let's retarget this to develop.

**Comment by danielmarbach** [comment]
done

**Comment by bording** [comment]
Now we just need PublicApiGenerator to remove blank lines automatically and we can get rid of `Filter` altogether!

Or maybe we just stop caring about blank lines being in the file and drop it now?

**Comment by danielmarbach** [comment]
Sent in https://github.com/JakeGinnivan/ApiApprover/pull/47/

**Comment by danielmarbach** [comment]
Nuget packages are still indexing. This might fail the first time

**Pull request merged**
