### PR TITLE
Issue JsonMessageSerializerBase - TypeNameHandling.None

### PR DESCRIPTION
**Pull request by marinkobabic**
The serializer method has different serializerSettings than the deserializer. This means the serializer has TypeNameHandling = TypeNameHandling.Auto but the deserializer has the TypeNameHandling = TypeNameHandling.None

So the deserializer can't benefit from the special json attributes $type, which has been created by the serializer, and causes the deserialization to fail.

The deserializer has the following condition

    var requiresDynamicDeserialization = mostConcreteType != null && mostConcreteType.IsInterface

In my case looks the event as following

IMyInterface

MyBaseClassProperty
So MyBaseClassProperty is an abstract class and can represent multiple concrete types. Because the event it self is an interface you are turning the TypeNameHandling to None. MyBaseClassProperty requires the TypeNameHandling = Auto to be able to deserialize.

An abstract class or interface can have properties which are also interfaces or abstract classes and so on

### CODE REVIEW

**Comment by johnsimons** [comment]
@Particular/nservicebus this PR is quite old, do we keep it open ?

**Comment by johnsimons** [comment]
@SeanFeldman you know being the Azure god, can you take a look at this PR and see if you want to bring it in ?

**Comment by SeanFeldman** [comment]
Haven't realized we're back in ancient Rome days :) will do @johnsimons

**Comment by danielmarbach** [comment]
@SeanFeldman @yvesgoeleven what happened with this?

**Comment by andreasohlund** [comment]
@tmasternak since you're most up to date with the json serializer can you look at what needs to be done here?

**Comment by tmasternak** [comment]
I verified the scenario and this is not supported indeed. However in my opinion introducing support for polymorphic properties on interfaces would go against 'make messages as simple as possible' principle. I think that we should not introduce those changes to jsonserializer.
That being said this scenario can be implemented using custom serializer that we do support. In other words: if you need this configure custom serialization.

**Comment by andreasohlund** [comment]
Makes sense, closing

**Pull request closed without merging**
