### PR TITLE
Remove circuit breaker from learning transports

### PR DESCRIPTION
**Pull request by andreasohlund**
Since we don't need the robustness and its better to surface issues
immediately.

@danielmarbach is it ok to throw out of the continuation like done here?

### CODE REVIEW

**Comment by danielmarbach** [comment]
Nooe this would transition the task into the faultet state, since it ks not observed it can teardown the appdomain (unobserved exception on scheduler)

**Comment by andreasohlund** [comment]
Figured that :) So  just call Environment.FailFast?

**Comment by andreasohlund** [comment]
Not that this is more of an experimental PR, not saying we should go ahead but I think the CB does more harm than good

**Comment by andreasohlund** [comment]
@danielmarbach decided to just invoke CriticalError immediately

**Comment by andreasohlund** [comment]
Convinced @timbussmann that this is a good idea :)

**Comment by andreasohlund** [comment]
@Particular/nservicebus-maintainers ready for review

**Pull request merged**
