### PR TITLE
remove RijndaelKeyIdentifier header

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by bording** [comment]
Not sure this can be called redundant yet, because it appears to be in use still: https://github.com/search?q=org%3AParticular+RijndaelKeyIdentifier&type=Code

I think we should remove those uses before removing this.

**Comment by SimonCropp** [comment]
@bording the majority of those are header doco. which should remain. and the only thing that should be using this is the property encryption package. ping  @Particular/encryption-maintainers

**Comment by MarcinHoppe** [comment]
@SimonCropp Please file a PR or issue against the encryption package as this change will break it.

**Comment by SimonCropp** [comment]
https://github.com/Particular/NServiceBus.Encryption.MessageProperty/pull/22

**Comment by MarcinHoppe** [comment]
Thanks, I'll merge when the build is green.

**Comment by bording** [comment]
Looks like SqlServer had a reference to the key that it shouldn't have because of it was scanning the wrong assembly for APIApprovals: https://github.com/Particular/NServiceBus.SqlServer/pull/400

**Comment by bording** [comment]
@Particular/nservicebus-maintainers Do we want to add this to the upgrade guide?

**Comment by andreasohlund** [comment]
Perhaps mention it here?
https://docs.particular.net/nservicebus/upgrades/externalize-encryption

**Pull request merged**
