### PR TITLE
custom finder support for unique properties

### PR DESCRIPTION
**Pull request by SimonCropp**
dont put mappings in the uniqueProperties collection if they are derived
from a custom finder. since they will not have a property name

### CODE REVIEW

**Comment by SimonCropp** [comment]
@johnsimons isnt this more correct than https://github.com/Particular/NServiceBus/commit/d5fc8552b050a53b0c03c086aa16f6ab5d0ad8db  ?

**Comment by johnsimons** [comment]
Not sure @SimonCropp 

IMO there is something off in the saga metadata.
Maybe the saga metadata should split, user explicit mappings vs Unique props, those are 2 different concerns IMO

**Comment by SimonCropp** [comment]
@johnsimons yeah agreed.  @andreasohlund any thoughts?

**Comment by andreasohlund** [comment]
> Maybe the saga metadata should split, user explicit mappings vs Unique
props, those are 2 different concerns IMO

+1

This makes it more explicit. And support us toggling "auto unique" for
mapped properties on and off.

**Comment by johnsimons** [comment]
So what is the plan of attack here ?

**Comment by johnsimons** [comment]
@andreasohlund I think we are waiting on your direction since the metamodel is your creation :wink:

**Comment by andreasohlund** [comment]
I'll get on a call with @SimonCropp and hash this one out

**Comment by johnsimons** [comment]
And document it on the issue so we all can contribute ;)

**Comment by johnsimons** [comment]
Was this merge a mistake?
It was my understanding that we are going to improve the metadata model to make unique props first level citizens and therefore most of these changes are invalidated.

**Comment by SimonCropp** [comment]
@johnsimons nope this wasnt a mistake. this PR ended up fixing the several existing bugs with the cross over between custom finders and message mapping.  and more importantly added several tests that will be valuable in any re-work going forward

**Comment by johnsimons** [comment]
That is cool @SimonCropp, but we were planning to use this PR and include also the changes to the metadata model.
Could you please next time ping the team before merging.

**Comment by andreasohlund** [comment]
We decided to do that in a separate pull since making correlated properties
unique is correct that we don't provide a way for users to mark things as
non-unique. We also decided to wait until after next weeks call on how the
persisters should use the metamodel to create the needed storage structures
since that will give us a better understanding of the problem.

The new pull should:

* Introduce a way to make correlated properties non-unique
* Most likely separate unique and correlation properties in the metamodel

The fail here was to not mention the above when we merged this pull, my bad!

**Pull request merged**
