### PR TITLE
[WIP]Full scan when conventions are in use

### LINKED ISSUE #4452: JSON Serializer can't handle messages with multiple inheritance
See https://github.com/Particular/docs.particular.net/pull/2290#issuecomment-264019883 for details on how to reproduce.

I've verified that JSON works if the endpoint has access to all types that is used on the message. It breaks when eg a subscriber only has access to a subset of the types like shown in the sample above.

Only reproduced on v6, need to verify how v5 behaves

### LINKED ISSUE #4567: Interface based message inheritance, conventions and json serializer does not play well together
### Problem
The combination of 

1) An interface based message inheriting another interface based message
2) Convention based definition of events
3) JsonSerializer 

does not work correctly. :(

If you publish a interface based message that inherits from another interface based message, a subscriber of the base message will blow up with a deserialization message stating that it can not instanciate the inherited type at publish time.

Changing to the xmlserializer, removing the inheritance, using classes instead of interfaces or inheriting from IEvent fixes the problem.

### Repro
Originally reported by user. Repro available [here](https://github.com/janovesk/NSBInheritanceBug).

### Code highlights
```
namespace Event
{
    public interface IBaseEvent
    {
        Guid Id { get; set; }
    }

    public interface IInheritedEvent : IBaseEvent
    {
    }
}
```
```
endpointConfiguration.UseSerialization<JsonSerializer>();
endpointConfiguration.Conventions().DefiningEventsAs(t => t.Namespace != null && t.Namespace.StartsWith("Event"));
```

```
public class BaseEventHandler : IHandleMessages<IBaseEvent>
{
    public Task Handle(IBaseEvent message, IMessageHandlerContext context)
    {
        return Task.CompletedTask;
    }
}
```

### Error message on subscriber receiving IInheritedEvent
```
2017-03-22 14:12:14.799 ERROR NServiceBus.RecoverabilityExecutor Moving message '64e5a7f3-1092-480f-818b-a73e00d9974f' to the error queue 'error' because processing failed due to an exception:
NServiceBus.MessageDeserializationException: An error occurred while attempting to extract logical messages from transport message 64e5a7f3-1092-480f-818b-a73e00d9974f ---> Newtonsoft.Json.JsonSerializationException: Could not create an instance of type Event.IInheritedEvent. Type is an interface or abstract class and cannot be instantiated. Path 'Id', line 1, position 6.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\MessageContext.cs:line 0
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\MessageContext.cs:line 0
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\MessageContext.cs:line 0
..
```

### PR DESCRIPTION
**Pull request by andreasohlund**
Alternative to https://github.com/Particular/NServiceBus/pull/4576/ where we tell the scanner to disable its optimization where only assemblies referencing NServiceBus would be considered if the user have specified a custom message convention.

Closes #4567

Most likely fixes #4452

### CODE REVIEW

**Comment by andreasohlund** [comment]
@Particular/nservicebus-maintainers @danielmarbach thoughts?

This way only users with conventions pay the increased startup time price

**Comment by timbussmann** [comment]
> Talking to @danielmarbach we think its to dangerous to always include non core reffing assemblies for unobtrusive users.

can you provide some more details on that statement?

**Comment by andreasohlund** [comment]
can you provide some more details on that statement?

>This way we can educate them of the dangers of doing the full scan:

>Increased startup time
>More type loading exceptions
>New types included that might interfere

**Comment by timbussmann** [comment]
> Increased startup time

as far as I remember from daniels tests, the scanning doesn't really take a noticeable amount of time during startup

> More type loading exceptions

does `Assembly.Load` really throw more exceptions than `Assembly.ReflectionOnlyLoad` (which we do any way)?

> New types included that might interfere

I can't come up with a scenario where this would really be an issue?

I don't like the `ScanAssembliesNotReferencingNServiceBusAsWell()` API. It would require quite an advanced knowledge of potentially affected users to be aware to configure this setting.

**Comment by andreasohlund** [comment]
@danielmarbach I'm about to close this PR, is it worth keeping the changes to the dynamic assembly stuff you think?

**Comment by danielmarbach** [comment]
I think it is a good addition to keep

**Comment by andreasohlund** [comment]
Ok, I'll pull that stuff out to a `Ignored` test that show how the scanner can miss some message types and raise a corresponding issue

**Comment by andreasohlund** [comment]
Replaced by https://github.com/Particular/NServiceBus/pull/4635

**Pull request closed without merging**
